export enum ToolType {
    DELETE = 'DELETE',
    ROTATE = 'ROTATE',
    HEIC_TO_PDF = 'HEIC_TO_PDF',
    EPUB_TO_PDF = 'EPUB_TO_PDF',
    PDF_TO_EPUB = 'PDF_TO_EPUB',
    MAKE_FILLABLE = 'MAKE_FILLABLE',
    CBR_TO_PDF = 'CBR_TO_PDF',
    SIGN = 'SIGN',
    ORGANIZE = 'ORGANIZE',
    PDF_TO_WORD = 'PDF_TO_WORD',
    WORD_TO_PDF = 'WORD_TO_PDF',
    PDF_PAGE_REMOVER = 'PDF_PAGE_REMOVER',
    FLATTEN = 'FLATTEN',
    CROP = 'CROP',
    COMPRESS = 'COMPRESS',
    MERGE = 'MERGE'
}

export enum AppState {
    HOME,
    SELECTING,
    PROCESSING,
    DONE,
    ERROR,
    EDITING_FORM
}

export type CurrentView = 'HOME' | 'PRICING' | 'PRIVACY' | 'TERMS' | 'SORRY' | 'HOW_TO' | 'SUPPORT' | 'MAKE_FILLABLE_INFO' | 'TOOL_PAGE';
