'use client';

import React from 'react';
import { QrCode, ScanLine, Tag, Smartphone, Package, Ticket } from 'lucide-react';
import { Language } from '../../../utils/i18n';
import { SEO } from '../../SEO';
import { PageLayout } from '../../PageLayout';
import { getGuideContent } from '../../../utils/guideContent';
import { MarkdownContent } from '../../MarkdownContent';
import { AuthorBio } from '../../AuthorBio';
import { ToolPromo } from '../../ToolPromo';
import { RelatedTools } from '../../RelatedTools';
import Link from 'next/link';

interface GuideProps {
    lang: Language;
}

const getLocalContent = (lang: string) => ({
    en: {
        seo_title: 'PDF Barcode & QR Code Generator Guide | Add Scannable Codes',
        seo_desc: 'Learn how to add professional, scannable barcodes and QR codes to PDFs. Vector-based codes for inventory, tickets, shipping labels, and more.',
        intro: `Adding **Barcodes** or **QR Codes** to PDFs is essential for modern business operations—from inventory management and event tickets to shipping labels and product packaging.

Our free **Barcode Generator** creates crisp, vector-based codes that remain perfectly scannable at any print size. Unlike blurry image-based barcodes, vector codes scale infinitely without losing quality.

### Who Needs This Tool?

*   **Warehouse & Inventory**: Generate SKU labels and asset tracking codes.
*   **Event Organizers**: Create scannable tickets and attendee badges.
*   **E-commerce & Shipping**: Print shipping labels with tracking barcodes.
*   **Retailers**: Generate product labels with UPC/EAN codes.
*   **Marketing Teams**: Add QR codes linking to campaigns, videos, or landing pages.
*   **Healthcare**: Create patient ID labels and medication tracking codes.`,
        sections: [
            {
                id: 'barcode-types',
                title: 'Common Barcode & QR Code Types',
                content: `**2D Codes (Two-Dimensional):**

*   **QR Code**: Most versatile. Holds URLs, text, vCards, WiFi credentials. Up to 4,000 characters. Self-error-correcting.
*   **Data Matrix**: Compact square code used in electronics and healthcare. Excellent for small labels.
*   **PDF417**: Stacked barcode used on driver's licenses and shipping labels. High capacity.

**1D Codes (Linear Barcodes):**

*   **Code 128**: Alphanumeric, used in logistics and shipping (GS1-128).
*   **Code 39**: Letters, numbers, and symbols. Common in automotive and defense.
*   **UPC-A/UPC-E**: 12-digit retail product codes (North America).
*   **EAN-13/EAN-8**: 13-digit retail codes (International).
*   **ITF-14**: Outer carton codes for shipping containers.

**Choosing the Right Code:**
| Use Case | Recommended Code |
|----------|-----------------|
| Website URL | QR Code |
| Product retail | UPC-A / EAN-13 |
| Shipping box | Code 128 / ITF-14 |
| Small electronics | Data Matrix |
| Event ticket | QR Code or Code 128 |
| WiFi password | QR Code |`
            },
            {
                id: 'vector-importance',
                title: 'Why Vector Barcodes Matter',
                content: `**The Problem with Image Barcodes:**
Never paste a blurry JPEG or PNG barcode into a PDF! Here's why:

*   **Scaling Issues**: Raster images become pixelated when enlarged
*   **Print Quality**: Low-resolution barcodes may not scan properly
*   **DPI Mismatch**: Screen resolution (72-96 DPI) differs from print (300 DPI)
*   **Scanner Failure**: Barcode lines may span multiple print dots, confusing scanners

**The Vector Solution:**
Vector barcodes (SVG or native PDF commands) are mathematically defined shapes:

*   ✅ Scale to any size without quality loss
*   ✅ Print at full printer resolution
*   ✅ Crisp, clean lines that scanners read perfectly
*   ✅ Smaller file size than high-resolution images

**Our Tool Creates Vector Codes:**
All barcodes generated by our tool are true vector graphics embedded directly in the PDF. They will scan perfectly whether printed on a tiny label or a large poster.`
            },
            {
                id: 'how-to',
                title: 'How to Add Barcodes to PDFs',
                content: `**Step 1: Choose Your Code Type**
Select from QR Code, Code 128, UPC, EAN, or other formats based on your needs.

**Step 2: Enter Your Data**
*   For QR codes: Enter URL, text, or contact info
*   For UPC/EAN: Enter the numeric product code
*   For Code 128: Enter alphanumeric text

**Step 3: Customize Appearance**
*   Set barcode size (width and height)
*   Choose colors (black/white recommended for scanning)
*   Add optional text label below the barcode

**Step 4: Generate & Position**
*   Preview the barcode before adding
*   Click on your PDF where you want it placed
*   Drag to resize and position precisely

**Step 5: Download**
Save your PDF with the embedded vector barcode.

**Pro Tips:**
*   Keep quiet zones (blank space around the barcode)
*   Test scan before printing large quantities
*   Use high contrast colors (dark bars on light background)
*   Avoid placing over images or patterns`
            },
            {
                id: 'use-cases',
                title: 'Common Use Cases',
                content: `**Inventory & Asset Management**
Generate labels with unique identifiers for tracking equipment, stock, and supplies.

**Event Tickets & Badges**
Create scannable tickets that can be verified at entry points with smartphone apps.

**Shipping & Logistics**
Add tracking barcodes to invoices, packing slips, and shipping labels.

**Product Labels**
Generate retail-ready UPC/EAN codes for products and packaging.

**Marketing Materials**
Add QR codes to brochures, business cards, and posters linking to websites or videos.

**Document Tracking**
Add unique barcodes to contracts, forms, and documents for filing and retrieval.

**Restaurant Menus**
Create QR codes linking to digital menus, ordering systems, or allergen info.

**Real Estate**
Add QR codes to property flyers linking to virtual tours or listing pages.`
            },
            {
                id: 'best-practices',
                title: 'Barcode Best Practices',
                content: `**Sizing Guidelines:**
| Code Type | Minimum Size | Recommended |
|-----------|-------------|-------------|
| QR Code | 1 cm × 1 cm | 2.5 cm × 2.5 cm |
| Code 128 | Height 0.5 cm | Height 1.5 cm |
| UPC-A | 2.9 cm × 2.1 cm | Standard retail size |
| Data Matrix | 0.3 cm × 0.3 cm | 1 cm × 1 cm |

**Color Recommendations:**
*   **Best**: Black bars on white background
*   **Good**: Dark colors on light backgrounds (dark blue on white)
*   **Avoid**: Red bars (some scanners use red light and won't see them)
*   **Never**: Low contrast combinations

**Quiet Zones:**
*   QR codes need blank space equal to 4 modules around the code
*   Linear barcodes need 10× the narrowest bar width on each side
*   Never crop or crowd the barcode

**Testing:**
*   Always test scan before mass printing
*   Test on multiple devices (smartphone, dedicated scanner)
*   Verify data accuracy by comparing scanned output to expected input`
            },
            {
                id: 'privacy',
                title: 'Privacy & Security',
                content: `**100% Local Processing**
Your barcode data is processed entirely in your browser. The content of your barcodes (URLs, product codes, tracking numbers) never leaves your device.

**Zero Data Collection**
We don't log, store, or transmit your barcode data. When you close the tab, all data is cleared.

**Secure QR Codes**
For sensitive data, consider:
*   Encrypting the QR content before encoding
*   Using URL shorteners that track clicks (for marketing)
*   Avoiding embedding passwords or sensitive data in plain text`
            },
            {
                id: 'troubleshooting',
                title: 'Troubleshooting',
                content: `**Problem: Barcode won't scan**
*Solution*: Ensure sufficient contrast and size. Check that quiet zones aren't cropped. Test print quality.

**Problem: Wrong data when scanned**
*Solution*: Verify you entered the correct data. Some codes have checksum requirements (UPC/EAN).

**Problem: Code looks blurry when printed**
*Solution*: Ensure you're using our vector output, not a screenshot. Check printer resolution settings.

**Problem: QR code contains wrong URL**
*Solution*: Include the full URL with https://. Test the QR code before adding to PDF.

**Problem: Barcode is too small to scan**
*Solution*: Increase the size. Most smartphone cameras need QR codes at least 2 cm wide.`
            },
            {
                id: 'faq',
                title: 'Frequently Asked Questions',
                content: `**What's the difference between QR codes and barcodes?**
Barcodes (1D) store data in varying bar widths and are read horizontally. QR codes (2D) store data in a pattern of squares and hold much more information.

**Can I create colored QR codes?**
Yes, but maintain high contrast. Dark foreground on light background works best. Avoid red foregrounds.

**What's the maximum data a QR code can hold?**
About 4,000 alphanumeric characters or 7,000 numeric digits. For practical use, keep URLs under 100 characters.

**Do I need to register barcodes?**
For UPC/EAN product codes, yes—you need a GS1 company prefix. For internal use (inventory, tickets), no registration needed.

**Can barcodes contain emojis or special characters?**
QR codes can encode any UTF-8 characters including emojis. Linear barcodes are limited to their defined character sets.

**How do I test if my barcode works?**
Use any free barcode scanner app on your smartphone. For linear barcodes, most camera apps can read them.

**What resolution should I export at?**
Our vector barcodes are resolution-independent. They will print at your printer's maximum quality automatically.

**Can I add multiple barcodes to one PDF?**
Yes! Add as many barcodes as needed to different positions in your document.

**Is this tool really free?**
Yes, 100% free with no watermarks or usage limits.

**Can I generate barcodes in bulk?**
Currently, barcodes are created one at a time. For batch generation, consider dedicated barcode software.`
            }
        ],
        breadcrumbs: {
            home: 'Home',
            guides: 'Guides',
            tool: 'Barcode Generator'
        }
    },
    fr: {
        seo_title: 'Guide Générateur Code-barres & QR Code PDF | Ajouter Codes Scannables',
        seo_desc: 'Apprenez à ajouter des codes-barres et QR codes professionnels scannables aux PDF. Codes vectoriels pour inventaire, billets, étiquettes.',
        intro: `Ajouter des **Codes-barres** ou **QR Codes** aux PDF est essentiel pour les opérations commerciales modernes—de la gestion d'inventaire aux billets d'événements et étiquettes d'expédition.

Notre **Générateur de Codes-barres** gratuit crée des codes vectoriels nets qui restent parfaitement scannables à n'importe quelle taille d'impression.

### Qui a besoin de cet outil ?

*   **Entrepôt et Inventaire** : Générez des étiquettes SKU et codes de suivi.
*   **Organisateurs d'événements** : Créez des billets et badges scannables.
*   **E-commerce et Expédition** : Imprimez des étiquettes avec codes de suivi.
*   **Détaillants** : Générez des étiquettes produits avec codes UPC/EAN.
*   **Équipes Marketing** : Ajoutez des QR codes vers vos campagnes.`,
        sections: [
            {
                id: 'barcode-types',
                title: 'Types de Codes-barres et QR Codes',
                content: `**Codes 2D :**
*   **QR Code** : Le plus polyvalent. Contient URL, texte, vCards. Jusqu'à 4 000 caractères.
*   **Data Matrix** : Code carré compact utilisé en électronique et santé.

**Codes 1D :**
*   **Code 128** : Alphanumérique, utilisé en logistique.
*   **UPC-A/EAN-13** : Codes produits de détail.`
            },
            {
                id: 'vector-importance',
                title: 'Pourquoi les Codes Vectoriels Sont Importants',
                content: `**Le problème avec les codes-barres image :**
Ne collez jamais un JPEG flou dans un PDF !

*   Les images deviennent pixelisées quand agrandies
*   La qualité d'impression peut empêcher le scan
*   Les lignes peuvent s'étaler et confondre les scanners

**Notre outil crée des codes vectoriels :**
✅ S'adaptent à n'importe quelle taille
✅ S'impriment à la résolution maximale
✅ Lignes nettes que les scanners lisent parfaitement`
            },
            {
                id: 'how-to',
                title: 'Comment Ajouter des Codes-barres aux PDF',
                content: `**Étape 1** : Choisissez le type de code
**Étape 2** : Entrez vos données
**Étape 3** : Personnalisez l'apparence
**Étape 4** : Générez et positionnez
**Étape 5** : Téléchargez

**Conseils :**
*   Gardez des zones de silence autour du code
*   Testez le scan avant d'imprimer en masse
*   Utilisez des couleurs à fort contraste`
            },
            {
                id: 'privacy',
                title: 'Confidentialité et Sécurité',
                content: `**Traitement 100% Local**
Vos données de code-barres sont traitées dans votre navigateur. Le contenu ne quitte jamais votre appareil.

**Zéro collecte de données**
Nous ne stockons pas vos données de codes-barres.`
            },
            {
                id: 'faq',
                title: 'Questions Fréquentes',
                content: `**Quelle différence entre QR codes et codes-barres ?**
Les codes-barres (1D) stockent des données dans des largeurs de barres. Les QR codes (2D) stockent dans un motif de carrés.

**Puis-je créer des QR codes colorés ?**
Oui, mais maintenez un fort contraste. Évitez les fonds rouges.

**Cet outil est-il vraiment gratuit ?**
Oui, 100% gratuit sans filigranes ou limites.`
            }
        ],
        breadcrumbs: {
            home: 'Accueil',
            guides: 'Guides',
            tool: 'Générateur Code-barres'
        }
    },
    pt: {
        seo_title: 'Guia Gerador de Código de Barras e QR Code para PDF | Adicionar Códigos Escaneáveis',
        seo_desc: 'Aprenda a adicionar códigos de barras e QR codes profissionais escaneáveis em PDFs. Códigos vetoriais para inventário, ingressos, etiquetas.',
        intro: `Adicionar **Códigos de Barras** ou **QR Codes** em PDFs é essencial para operações comerciais modernas—de gestão de inventário a ingressos de eventos e etiquetas de envio.

Nosso **Gerador de Código de Barras** gratuito cria códigos vetoriais nítidos que permanecem perfeitamente escaneáveis em qualquer tamanho de impressão.

### Quem precisa desta ferramenta?

*   **Armazém e Inventário**: Gere etiquetas SKU e códigos de rastreamento.
*   **Organizadores de eventos**: Crie ingressos e crachás escaneáveis.
*   **E-commerce e Envio**: Imprima etiquetas com códigos de rastreamento.
*   **Varejistas**: Gere etiquetas de produtos com códigos UPC/EAN.
*   **Equipes de Marketing**: Adicione QR codes para suas campanhas.`,
        sections: [
            {
                id: 'barcode-types',
                title: 'Tipos de Códigos de Barras e QR Codes',
                content: `**Códigos 2D:**
*   **QR Code**: O mais versátil. Contém URL, texto, vCards. Até 4.000 caracteres.
*   **Data Matrix**: Código quadrado compacto usado em eletrônicos e saúde.

**Códigos 1D:**
*   **Code 128**: Alfanumérico, usado em logística.
*   **UPC-A/EAN-13**: Códigos de produtos de varejo.`
            },
            {
                id: 'vector-importance',
                title: 'Por que Códigos Vetoriais São Importantes',
                content: `**O problema com códigos de barras em imagem:**
Nunca cole um JPEG borrado em um PDF!

*   Imagens ficam pixelizadas quando ampliadas
*   A qualidade de impressão pode impedir a leitura
*   As linhas podem se espalhar e confundir os leitores

**Nossa ferramenta cria códigos vetoriais:**
✅ Escalam para qualquer tamanho
✅ Imprimem na resolução máxima
✅ Linhas nítidas que os leitores leem perfeitamente`
            },
            {
                id: 'how-to',
                title: 'Como Adicionar Códigos de Barras em PDFs',
                content: `**Passo 1**: Escolha o tipo de código
**Passo 2**: Insira seus dados
**Passo 3**: Personalize a aparência
**Passo 4**: Gere e posicione
**Passo 5**: Baixe

**Dicas:**
*   Mantenha zonas de silêncio ao redor do código
*   Teste a leitura antes de imprimir em massa
*   Use cores de alto contraste`
            },
            {
                id: 'privacy',
                title: 'Privacidade e Segurança',
                content: `**Processamento 100% Local**
Seus dados de código de barras são processados no navegador. O conteúdo nunca sai do seu dispositivo.

**Zero coleta de dados**
Não armazenamos seus dados de códigos de barras.`
            },
            {
                id: 'faq',
                title: 'Perguntas Frequentes',
                content: `**Qual a diferença entre QR codes e códigos de barras?**
Códigos de barras (1D) armazenam dados em larguras de barras. QR codes (2D) armazenam em um padrão de quadrados.

**Posso criar QR codes coloridos?**
Sim, mas mantenha alto contraste. Evite fundos vermelhos.

**Esta ferramenta é realmente gratuita?**
Sim, 100% gratuita sem marcas d'água ou limites.`
            }
        ],
        breadcrumbs: {
            home: 'Início',
            guides: 'Guias',
            tool: 'Gerador de Código de Barras'
        }
    }
});

export const BarcodeGeneratorGuide: React.FC<GuideProps> = ({ lang }) => {
    const guideContent = getGuideContent(lang);
    const localContent = getLocalContent(lang);
    const t = (localContent as any)[lang] || (localContent as any).en;

    return (
        <div className="bg-white dark:bg-gray-950">
            <SEO
                title={t.seo_title}
                description={t.seo_desc}
                canonicalPath={`/${lang}/guides/barcode-generator`}
                lang={lang}
                breadcrumbs={[
                    { name: t.breadcrumbs.home, path: lang === 'en' ? '/' : `/${lang}` },
                    { name: t.breadcrumbs.guides, path: `/${lang}/guides` },
                    { name: t.breadcrumbs.tool, path: `/${lang}/guides/barcode-generator` }
                ]}
            />
            <PageLayout
                title={lang === 'fr' ? 'Générer Codes-barres PDF' : (lang === 'pt' ? 'Gerar Códigos de Barras em PDF' : 'Generate PDF Barcodes')}
                subtitle={lang === 'fr' ? 'Ajoutez des codes scannables à vos documents.' : (lang === 'pt' ? 'Adicione códigos escaneáveis aos seus documentos.' : 'Add scannable codes to your documents.')}
                icon={<QrCode size={32} />}
                breadcrumbs={[
                    { name: t.breadcrumbs.home, href: lang === 'en' ? '/' : `/${lang}` },
                    { name: t.breadcrumbs.guides, href: `/${lang}/guides` },
                    { name: t.breadcrumbs.tool, href: `/${lang}/guides/barcode-generator` }
                ]}
            >
                <div className="w-full py-4 sm:py-6 md:py-8">
                    <ToolPromo tool="barcode-generator" lang={lang} />
                    <MarkdownContent content={t.intro} />

                    {t.sections.map((section: any) => (
                        <section key={section.id} className="mb-12">
                            <h2 className="text-2xl font-bold mb-4 flex items-center gap-2">
                                <div className="w-2 h-8 bg-canada-red rounded-full" />
                                {section.title}
                            </h2>
                            <div className="prose dark:prose-invert max-w-none text-gray-600 dark:text-gray-400">
                                <MarkdownContent content={section.content} />
                            </div>
                        </section>
                    ))}

                    <div className="mt-12">
                        <RelatedTools lang={lang} currentPath={`/${lang}/guides/barcode-generator`} category="edit" />
                    </div>

                    <div className="mt-16 pt-8 border-t border-gray-100 dark:border-gray-800">
                        <AuthorBio lang={lang} />
                    </div>
                </div>
            </PageLayout>
        </div>
    );
};
