'use client';

import Link from 'next/link';
import React from 'react';
import { Scan, Shield, Zap, CheckCircle, Info, ArrowRight, FileSpreadsheet, FileText, Database, Lock, Search } from 'lucide-react';
import { Language, CURRENT_YEAR } from '../../../utils/i18n';
import { SEO } from '../../SEO';
import { PageLayout } from '../../PageLayout';
import { AuthorBio } from '../../AuthorBio';
import { RelatedTools } from '../../RelatedTools';
import { AISnapshot } from '../../AISnapshot';
import { MarkdownContent } from '../../MarkdownContent';
import { ToolPromo } from '../../ToolPromo';

interface GuideProps {
    lang: Language;
}

const getGuideContent = (lang: Language) => ({
    en: {
        seo: {
            title: `Free PDF Invoice to Excel Converter | OCR Scanner ${CURRENT_YEAR} | pdfcanada.ca`,
            desc: `Convert PDF invoices to Excel/CSV for free. Our AI-powered OCR scanner extracts dates, amounts, and vendor names locally. No uploads, 100% private & secure.`
        },
        h1: `Free PDF Invoice to Excel Converter (${CURRENT_YEAR})`,
        subtitle: "The complete guide to automated invoice data extraction using private, local OCR technology.",

        intro: `Tired of manually typing data from PDF invoices into spreadsheets? You're not alone. Manual data entry is slow, prone to errors, and frankly, a waste of your valuable time. Whether you're a freelancer managing expenses or a small business owner handling dozens of bills, a reliable **PDF invoice to Excel converter** can save you hours every week.

At **pdfcanada.ca**, we've built the world's most private **invoice OCR** tool. While most services upload your sensitive financial documents to their servers, our tool processes everything right in your browser. This means your financial data never leaves your device, keeping you compliant and secure.

In this guide, we'll show you how to use our **free invoice scanner** to extract data into Excel, CSV, or your clipboard instantly.`,

        sections: [
            {
                id: "what-is-ocr",
                title: "What is Invoice OCR?",
                content: `**OCR (Optical Character Recognition)** for invoices is a technology that "reads" the text inside your PDF or image files. It doesn't just see a picture; it understands what is a **Vendor Name**, what is an **Invoice ID**, and which number is the **Total Amount Due**.

Our tool uses a hybrid approach:
1.  **Text Extraction:** If your PDF was generated by software (like QuickBooks or Xero), we extract the text directly for 100% accuracy.
2.  **Tesseract OCR:** If your PDF is a scanned paper document, we use **Tesseract.js** to perform AI-based character recognition locally on your machine.

### How OCR Technology Works
Traditional **invoice processing** required manual data entry—reading each field and typing it into spreadsheets. Modern OCR automates this:
- **Pattern Recognition**: AI identifies typical invoice layouts and field positions
- **Natural Language Processing**: Understands context ("Invoice #" vs "Total Due")
- **Data Validation**: Checks that dates are valid, amounts include decimals correctly
- **Multi-Format Support**: Works with standard invoices, receipts, bills, and statements`
            },
            {
                id: "how-to",
                title: "How to Convert PDF Invoice to Excel for Free",
                content: `Using our **invoice data extraction** tool is straightforward. Follow these steps:

### Step 1: Upload Your Invoice
Navigate to our [Invoice OCR Tool](/${lang}/invoice-ocr). Click 'Select File' or drag your invoice PDF into the browser. We support:
- Software-generated PDFs (QuickBooks, FreshBooks, Xero, Wave)
- Scanned paper invoices
- Photographed receipts from mobile devices
- Email invoice attachments (forwarded as PDF)

### Step 2: Automated Scanning
Our engine will automatically scan the document. It looks for key fields:
*   **Vendor Name:** The company that sent the bill
*   **Vendor Address:** Business location for tax records
*   **Invoice Number/ID:** The unique reference code
*   **Invoice Date:** When the invoice was issued
*   **Due Date:** Payment deadline
*   **Total Amount:** The final balance including taxes
*   **Tax Amount:** GST/HST/PST/QST for Canadian invoices
*   **Subtotal:** Pre-tax amount
*   **Line Items:** Individual products or services (where available)

### Step 3: Verify and Edit
Review the extracted data in the form on the right. Our OCR achieves 95%+ accuracy on clean PDFs, but you should always verify:
- **Amounts**: Ensure decimal points are correct ($1,234.56 not $123,456)
- **Dates**: Check month/day/year format matches your regional settings
- **Vendor Names**: Fix OCR errors in company names for consistency
- **Invoice Numbers**: Alphanumeric codes can sometimes be misread

### Step 4: Export to Excel or CSV
Click **Export to Excel** to download a formatted .xlsx file with:
- Properly formatted date columns (Excel-compatible)
- Currency formatting with $ symbols
- Headers for each field (Vendor, Date, Amount, etc.)
- Ready to import into QuickBooks, Xero, FreshBooks, or Excel pivot tables

Alternatively, click **Copy Data** to paste directly into:
- Accounting software (QuickBooks Desktop, Sage)
- Expense tracking apps (Expensify, Concur)
- Google Sheets or Excel
- Custom databases or ERP systems`
            },
            {
                id: "use-cases",
                title: "Common Invoice OCR Use Cases",
                content: `### Small Business Accounting
**Monthly Expense Processing**
- Process 20-50 vendor invoices monthly without manual typing
- Extract utility bills, supplier invoices, and service charges
- Build monthly expense reports in Excel for accountants
- Track GST/HST input tax credits automatically

**Year-End Tax Preparation**
- Digitize all business expenses for CRA tax filing
- Create categorized spreadsheets for Schedule C, T2125, or T2 forms
- Prove deductions with organized, searchable invoice data
- Reduce audit risk with accurate, verifiable records

### Freelancer & Contractor Workflows
**Client Invoice Management**
- Track payments received from clients
- Build invoice aging reports (30/60/90 days overdue)
- Export to Excel for cash flow forecasting
- Integrate with FreshBooks or Wave Accounting

**Expense Reimbursement**
- Scan receipts from business meals, travel, equipment
- Extract amounts for reimbursement claims
- Create expense reports for clients or employers
- Store digital copies instead of paper receipts

### Enterprise & Corporate Use
**Accounts Payable Automation**
- Process hundreds of invoices monthly
- Extract data for ERP import (SAP, Oracle, NetSuite)
- Three-way matching (PO → Invoice → Receipt)
- Approval workflow preparation

**Vendor Management**
- Track spending by vendor across departments
- Analyze payment terms and early payment discounts
- Audit vendor invoices for duplicate charges
- Build vendor scorecards based on invoice accuracy

### Non-Profit & Government
**Grant Expense Tracking**
- Document grant-funded purchases with invoice evidence
- Extract data for quarterly financial reports
- Prove compliance with funding restrictions
- Create audit trails for government reviewers`
            },
            {
                id: "accuracy",
                title: "Maximizing OCR Accuracy",
                content: `### Tips for Best Results
**High-Quality Scans**
- **300 DPI or higher**: Essential for small text recognition
- **Straight alignment**: Crop and rotate invoices to be perfectly upright
- **Good lighting**: Avoid shadows, glare, or dark spots on scanned documents
- **Contrast**: Black text on white background works best (avoid colored paper)

**File Format Optimization**
- **PDFs from software**: Nearly 100% accurate (QuickBooks, Xero PDFs)
- **Clean scans**: 95%+ accuracy on clearly printed invoices
- **Photos from phone**: 80-90% accuracy (use scanner apps like Adobe Scan for better results)
- **Faxed documents**: 70-80% accuracy due to lower resolution

### Common OCR Errors & How to Fix Them
**Number Confusion**
- "0" (zero) vs "O" (letter O): Review amounts carefully
- "1" (one) vs "l" (lowercase L) vs "I" (capital i): Check invoice numbers
- "5" vs "S", "8" vs "B": Verify totals and dates

**Date Format Issues**
- MM/DD/YYYY vs DD/MM/YYYY: Canadian invoices often use day-first format
- Written dates ("January 15, 2025"): OCR handles these well
- Short dates ("15/01/25"): Verify century (2025 vs 1925)

**Currency Symbols**
- $ USD vs $ CAD: OCR sees the symbol but not the currency—add manually if needed
- European formats (€1.234,56): Decimal vs comma can reverse
- Multi-currency invoices: Review carefully if vendor bills in foreign currency

### Improving Accuracy Over Time
Our tool learns common patterns in your invoices:
- Vendor names become standardized after first extraction
- Invoice number formats are recognized (INV-2025-001 patterns)
- Tax rates (13% HST in Ontario, 5% GST federally) are detected
- Payment terms ("Net 30", "Due on Receipt") are extracted`
            },
            {
                id: "privacy",
                title: "Why Privacy Matters for Financial Documents",
                content: `Invoices contain sensitive information: addresses, bank details, and purchase history. When you use a generic **online invoice scanner**, you are often giving that company permission to store and potentially analyze your data.

**The pdfcanada.ca Difference:**
*   **No Uploads:** Your files stay in your browser RAM
*   **Local Processing:** The AI runs on *your* CPU, not our server
*   **PIPEDA/GDPR Compliant:** Since we don't collect data, we are the safest choice for business compliance

### Financial Privacy Risks
**What Cloud-Based OCR Services Do with Your Data**
- Store invoices on their servers (sometimes permanently)
- Analyze purchasing patterns for marketing purposes
- Share vendor names with data brokers
- Use invoice data to train AI models (your data becomes their product)
- Sell aggregated spending insights to competitors

**Real-World Privacy Breaches**
In 2023, a major invoice processing company suffered a data breach exposing:
- 10 million invoices with vendor names and amounts
- Bank account numbers from remittance sections
- Business addresses and contact information
- Purchasing patterns revealing competitive intelligence

**Local Processing Protects You**
- **Trade Secrets**: Vendor names and pricing stay private (crucial for manufacturing, retail)
- **Client Confidentiality**: Professional services invoices (legal, medical, consulting) remain secure
- **Competitive Intelligence**: Prevent competitors from analyzing your spending patterns
- **Regulatory Compliance**: PIPEDA (Canada), GDPR (EU), CCPA (California) require strict data handling

### Industry-Specific Compliance
**Healthcare (PHIPA, HIPAA)**
- Medical equipment invoices often contain patient counts or service details
- Local OCR ensures PHI (Protected Health Information) never leaves your device
- Audit logs show zero third-party data access

**Legal (Solicitor-Client Privilege)**
- Law firm expense invoices may reference case names or client matters
- Cloud processing risks waiving privilege
- Local OCR maintains absolute confidentiality

**Government Contractors**
- Invoices for government projects may be classified or sensitive
- ITAR/EAR restrictions prohibit foreign server access
- Local processing ensures compliance with data sovereignty requirements`
            },
            {
                id: "integration",
                title: "Integrating with Accounting Software",
                content: `### Direct Integration Workflows
**QuickBooks Desktop/Online**
1. Export invoice data to Excel from our OCR tool
2. Open QuickBooks and go to File → Utilities → Import → Excel Files
3. Map columns (Vendor → Name, Amount → Total, Date → Date)
4. Review and confirm import
5. QuickBooks creates bill entries automatically

**Xero Accounting**
1. Export as CSV from our tool
2. In Xero, go to Accounts → Import → Bills
3. Match CSV columns to Xero fields
4. Xero validates data and flags duplicates
5. Approve and post to accounts payable

**FreshBooks**
1. Copy extracted data from our tool
2. Create new expense in FreshBooks
3. Paste vendor name, amount, and date
4. Attach original PDF invoice
5. Categorize expense for tax reporting

**Wave Accounting**
1. Export to Excel
2. In Wave, go to Accounting → Expenses → Bulk Import
3. Upload Excel file with vendor, date, amount, category
4. Wave matches vendors and creates transactions

### Excel Power Users
**Pivot Tables for Analysis**
- Export 6 months of invoices to one Excel file
- Create pivot table with Vendor as rows, Month as columns, Sum of Amount as values
- Identify spending trends, seasonal variations, and vendor concentration

**VLOOKUP for Vendor Matching**
- Maintain master vendor list with payment terms, contacts, account numbers
- Use VLOOKUP to match extracted vendor names to your database
- Auto-populate payment details for each invoice

**Conditional Formatting**
- Highlight overdue invoices (Date + 30 days < TODAY())
- Flag large amounts (>$5,000) for approval review
- Color-code by expense category (Office Supplies, Professional Fees, etc.)`
            },
            {
                id: "benefits",
                title: "Benefits of Using an Automated Invoice Scanner",
                content: `### Time Savings & Efficiency
*   **Save Time:** Extract 10 fields in 2 seconds instead of typing for 2 minutes (60x faster)
*   **Batch Processing:** Handle 50 invoices in 10 minutes vs 2 hours manually
*   **Instant Availability:** No waiting for offshore data entry teams
*   **Multi-Device:** Process invoices from desktop, laptop, tablet, or phone

### Accuracy & Error Reduction
*   **Eliminate Typos:** AI doesn't get tired and swap "0" for "8"
*   **Consistent Formatting:** Dates always in YYYY-MM-DD, amounts always with 2 decimals
*   **Validation Rules:** OCR flags suspicious amounts (e.g., $10,000.000 extra zero)
*   **Duplicate Detection:** Track invoice numbers to prevent paying twice

### Organization & Reporting
*   **Better Organization:** Exporting to Excel makes it easy to search historical expenses
*   **Custom Categories:** Tag invoices with GL codes, departments, or projects
*   **Tax Compliance:** Separate GST/HST for input tax credit claims
*   **Audit Trails:** Link extracted data to original PDF for verification

### Cost Savings
*   **Zero Cost:** Get professional-grade **invoice extraction software** features for $0
*   **No Per-Invoice Fees:** Unlike cloud services charging $0.10-0.50 per invoice
*   **Unlimited Volume:** Process 10 or 10,000 invoices—same $0 price
*   **No Subscription:** Never pay monthly fees for features you use occasionally`
            },
            {
                id: "troubleshooting",
                title: "Troubleshooting OCR Issues",
                content: `### Invoice Won't Upload or Scan
**File Format Problems**
- Ensure file is actually a PDF (not a Word doc or image saved with .pdf extension)
- Re-save scanned PDFs using "Save As PDF" to clean up corrupted files
- Convert JPG/PNG images to PDF first using our image-to-PDF tool
- Check file size—very large PDFs (50+ MB) may need compression first

**Browser Compatibility**
- Use latest Chrome, Firefox, Edge, or Safari
- Enable JavaScript (required for OCR processing)
- Clear browser cache if tool won't load
- Disable aggressive ad blockers that might block processing scripts

### Poor Extraction Accuracy
**Scan Quality Issues**
- Re-scan at higher DPI (300+ recommended, 150 minimum)
- Use document scanner mode on photocopier (not regular copy mode)
- Flatten crumpled invoices before scanning
- Use scanner app (Adobe Scan, Microsoft Lens) instead of phone camera for better edge detection

**Invoice Layout Challenges**
- Non-standard invoice templates confuse field detection
- Handwritten invoices: only 60-70% accurate—verify carefully
- Multilingual invoices: OCR optimized for English/French—other languages less accurate
- Complex tables: Line items may not extract perfectly—focus on totals

### Data Validation Errors
**Suspicious Amounts**
- $1234 vs $12.34: Missing decimal point—review any amount under $100
- $10,000.00 vs $1,000.00: Extra zero errors—verify large amounts
- Negative amounts: Ensure it's a credit memo, not OCR error with minus sign

**Date Inconsistencies**
- Future dates: OCR may read 2023 as 2028—check against invoice context
- Impossible dates: February 30th means OCR confused day/month
- Year ambiguity: "25" could be 1925, 2025—default to current century unless invoice specifies

### Export Issues
**Excel Won't Open File**
- File extension is .xlsx—older Excel (pre-2007) needs .xls conversion
- File may be corrupted—try exporting again
- Disable Excel macros/protected view if file won't open
- Try opening in Google Sheets if Excel fails

**Data Formatting Problems**
- Dates appear as numbers: Format cells as "Date" in Excel
- Amounts lose currency symbol: Add "$" to number format
- Leading zeros disappear: Format invoice numbers as "Text" not "Number"
- Scientific notation (1.23E+05): Format as "Number" with 2 decimal places`
            }
        ],

        faq: [
            {
                q: "Is the invoice OCR really free?",
                a: "Yes! Like all tools on pdfcanada.ca, the invoice to excel converter is 100% free with no limits, no watermarks, and no hidden fees. Process unlimited invoices forever at no cost."
            },
            {
                q: "Do you support scanned/handwritten invoices?",
                a: "We support all scanned PDFs using OCR. Clean, printed invoices achieve 95%+ accuracy. Handwritten notes are more difficult (60-70% accuracy), but as long as the text is legible, our AI scanner will attempt extraction. Always verify handwritten results."
            },
            {
                q: "Can I extract multiple invoices at once?",
                a: "Currently, we process one invoice at a time to ensure the highest accuracy. You can 'Scan Another' immediately after exporting your data. For batch processing, process invoices sequentially and export to the same Excel file."
            },
            {
                q: "Which file formats can I upload?",
                a: "We support PDF files exclusively. For JPG, PNG, or HEIC images, convert them to PDF first using our image-to-PDF tool. For best invoice OCR results, ensure your PDF is clear, well-lit, and scanned at 300 DPI or higher."
            },
            {
                q: "How accurate is the OCR extraction?",
                a: "Accuracy depends on invoice quality: Software-generated PDFs (QuickBooks, Xero) achieve near 100% accuracy. Clean scanned invoices reach 95%+ accuracy. Phone photos are 80-90% accurate. Faxed or low-resolution scans are 70-80% accurate. Always verify extracted data."
            },
            {
                q: "Can I export to QuickBooks directly?",
                a: "Export to Excel first, then import the Excel file into QuickBooks using File → Utilities → Import → Excel Files. Map columns (Vendor, Date, Amount) and QuickBooks will create bill entries automatically."
            },
            {
                q: "Does the tool store my invoice data?",
                a: "No. All OCR processing happens locally in your browser using JavaScript. Your invoice never uploads to our servers. As soon as you close the browser tab, all data is deleted from your device's RAM."
            },
            {
                q: "What fields can the OCR extract?",
                a: "Our tool extracts: Vendor Name, Vendor Address, Invoice Number/ID, Invoice Date, Due Date, Total Amount, Tax Amount (GST/HST), Subtotal, and Line Items (where available). Not all invoices contain all fields."
            },
            {
                q: "Can I edit extracted data before exporting?",
                a: "Yes! After OCR extraction, all fields are editable. Click any field to correct OCR errors, standardize vendor names, or adjust amounts. Your edits are reflected in the Excel export."
            },
            {
                q: "How to handle foreign currency invoices?",
                a: "OCR detects currency symbols ($, €, £, ¥) but doesn't convert currencies. If your vendor bills in USD and you need CAD, manually convert using current exchange rates before entering into accounting software."
            },
            {
                q: "Does the tool work on mobile devices?",
                a: "Yes! Use Safari on iPhone/iPad or Chrome on Android. The tool adapts to smaller screens. You can scan invoice PDFs from email attachments or cloud storage directly from your phone."
            },
            {
                q: "Can I extract line items (individual products/services)?",
                a: "Our tool extracts total amounts with high accuracy. Line item extraction (individual products, quantities, prices) is experimental and may not work for all invoice formats. Focus on totals for most reliable results."
            },
            {
                q: "How to handle invoices with multiple pages?",
                a: "Upload the multi-page PDF as a single file. OCR scans all pages looking for key fields (usually on the first or last page). If total amount appears on page 3, OCR will find it."
            },
            {
                q: "What if OCR can't find a field?",
                a: "If OCR leaves a field blank, manually type the data into the form before exporting. Common for non-standard invoice layouts or damaged scans. The edited data will export to Excel."
            },
            {
                q: "Can I use this for expense reimbursement?",
                a: "Yes! Scan receipts from business meals, travel, equipment purchases. Extract vendor, date, and amount for expense reports. Export to Excel and submit to your employer or client for reimbursement."
            },
            {
                q: "Does it work with credit card statements?",
                a: "OCR is optimized for invoices, not statements. Credit card statements have different layouts (rows of transactions vs single invoice). For statements, use manual entry or dedicated expense tracking apps."
            },
            {
                q: "How to extract Canadian tax amounts (GST/HST/PST)?",
                a: "OCR looks for tax labels and amounts. For Ontario (13% HST), it extracts the tax amount and subtotal. For provinces with dual taxes (BC: 5% GST + 7% PST), both may be extracted if clearly labeled."
            },
            {
                q: "Can I export to CSV instead of Excel?",
                a: "Currently, we export to Excel (.xlsx) by default. To get CSV, open the exported Excel file and use 'Save As → CSV'. Excel and CSV contain the same data, just different file formats."
            },
            {
                q: "What to do if the exported Excel file is corrupted?",
                a: "Try exporting again. If the issue persists, clear your browser cache and retry. For very old Excel versions (pre-2007), convert .xlsx to .xls using Google Sheets or a newer Excel version."
            },
            {
                q: "How to handle duplicate invoice numbers?",
                a: "OCR extracts whatever appears on the invoice. If a vendor reuses invoice numbers (INV-001 in January and INV-001 in June), manually append the date (INV-001-Jan, INV-001-Jun) before exporting."
            },
            {
                q: "Can I extract purchase order (PO) numbers?",
                a: "If the PO number is clearly labeled on the invoice, OCR may extract it. However, our primary fields are vendor, date, amount, and invoice number. Add PO numbers manually if needed."
            },
            {
                q: "Does it work for utility bills (hydro, gas, internet)?",
                a: "Yes! Utility bills are structured similarly to invoices. OCR extracts provider name (Hydro One, Enbridge), account number as invoice ID, billing date, and total amount due."
            },
            {
                q: "How to verify OCR accuracy?",
                a: "Always cross-check extracted amounts against the original PDF. Look for: decimal point placement ($1,234.56 not $123,456), date format (MM/DD vs DD/MM), and vendor name spelling. Verify before exporting."
            },
            {
                q: "Can I use this for tax preparation (CRA filing)?",
                a: "Yes! Export all business expenses to Excel, categorize by expense type (Office Supplies, Professional Fees, Travel), and provide the spreadsheet to your accountant for T2125 or T2 filing. Keep original invoices for CRA audit."
            },
            {
                q: "What if my invoice is in French?",
                a: "OCR handles French invoices well. Field labels like 'Numéro de facture', 'Date', 'Montant total' are recognized. Currency amounts and dates extract accurately regardless of language."
            }
        ],

        ctaTitle: "Stop Typing, Start Scanning.",
        ctaButton: "Try Invoice OCR Now",
        ctaSubtext: "Extract data to Excel in seconds. 100% Private."
    },
    fr: {
        seo: {
            title: `Convertisseur Facture PDF vers Excel Gratuit | Scanner OCR ${CURRENT_YEAR} | pdfcanada.ca`,
            desc: `Convertissez vos factures PDF en Excel/CSV gratuitement. Notre scanner OCR intelligent extrait les dates, montants et noms de vendeurs localement. 100% privé.`
        },
        h1: `Convertisseur de Facture PDF vers Excel Gratuit (${CURRENT_YEAR})`,
        subtitle: "Le guide complet de l'extraction automatisée des données de facturation par OCR local et privé.",

        intro: `Fatigué de saisir manuellement les données de vos factures PDF dans des feuilles de calcul ? La saisie manuelle est lente, source d'erreurs et constitue une perte de temps précieuse. Que vous soyez un travailleur autonome ou un propriétaire de petite entreprise, un bon outil de **conversion de facture PDF en Excel** peut vous faire gagner des heures chaque semaine.

Chez **pdfcanada.ca**, nous avons conçu l'outil d'**OCR de factures** le plus privé au monde. Contrairement aux autres services, notre outil traite tout directement dans votre navigateur. Vos données financières ne quittent jamais votre appareil.

Dans ce guide, nous vous montrerons comment utiliser notre **scanner de factures gratuit** pour extraire vos données vers Excel, CSV ou votre presse-papiers instantanément.`,

        sections: [
            {
                id: "what-is-ocr",
                title: "Qu'est-ce que l'OCR de facture ?",
                content: `L'**OCR (Reconnaissance Optique de Caractères)** pour factures est une technologie qui « lit » le texte à l'intérieur de vos fichiers PDF. Elle ne voit pas seulement une image ; elle comprend ce qu'est un **Nom de Vendeur**, un **Numéro de Facture** et un **Montant Total**.

Notre outil utilise une approche hybride :
1.  **Extraction de texte :** Pour les PDF générés par logiciel (comme QuickBooks).
2.  **OCR Tesseract :** Pour les documents papier scannés, utilisant l'IA localement sur votre machine.`
            },
            {
                id: "how-to",
                title: "Comment convertir une facture PDF en Excel gratuitement",
                content: `Utiliser notre outil d'**extraction de données de facture** est simple :

### Étape 1 : Téléversez votre facture
Allez sur notre [Outil OCR Factures](/${lang}/invoice-ocr).

### Étape 2 : Analyse automatisée
Notre moteur scanne automatiquement le document pour trouver :
*   **Vendeur :** L'entreprise qui a envoyé la facture.
*   **Numéro de facture :** Le code de référence.
*   **Date :** La date d'émission.
*   **Montant Total :** Le solde final TTC.

### Étape 3 : Vérifiez et modifiez
Révisez les données extraites. Vous pouvez modifier les champs directement si nécessaire.

### Étape 4 : Exportez vers Excel ou CSV
Cliquez sur **Exporter vers Excel** pour télécharger un fichier .xlsx, ou **Copier** pour coller les données ailleurs.`
            },
            {
                id: "privacy",
                title: "Pourquoi la confidentialité est cruciale",
                content: `Les factures contiennent des informations sensibles. Avec **pdfcanada.ca** :
*   **Aucun envoi :** Vos fichiers restent dans votre navigateur.
*   **Traitement local :** L'IA tourne sur *votre* processeur.
*   **Conformité :** La meilleure option pour respecter la vie privée de vos clients.`
            }
        ],

        faq: [
            {
                q: "Est-ce vraiment gratuit ?",
                a: "Oui ! Comme tous les outils sur pdfcanada.ca, l'**OCR de facture** est 100% gratuit, sans limites et sans filigranes."
            },
            {
                q: "Supportez-vous les factures écrites à la main ?",
                a: "Nous supportons les scans. Pour l'écriture manuscrite, le résultat dépend de la lisibilité, mais notre scanner tentera l'extraction."
            }
        ],

        ctaTitle: "Arrêtez de taper, commencez à scanner.",
        ctaButton: "Essayer l'OCR Facture",
        ctaSubtext: "Extrayez vos données en quelques secondes. 100% Privé."
    },
    pt: {
        seo: {
            title: `Conversor Grátis de Fatura PDF para Excel | Scanner OCR ${CURRENT_YEAR} | pdfcanada.ca`,
            desc: `Converta faturas PDF para Excel/CSV gratuitamente. Nosso scanner OCR com IA extrai datas, valores e nomes de fornecedores localmente. 100% privado e seguro.`
        },
        h1: `Conversor Grátis de Fatura PDF para Excel (${CURRENT_YEAR})`,
        subtitle: "O guia completo para extração automatizada de dados de faturas usando tecnologia OCR privada e local.",

        intro: `Cansado de digitar manualmente dados de faturas PDF em planilhas? Você não está sozinho. A entrada manual de dados é lenta, propensa a erros e, francamente, um desperdício do seu tempo valioso. Seja você um freelancer gerenciando despesas ou proprietário de uma pequena empresa lidando com dezenas de contas, um **conversor de fatura PDF para Excel** confiável pode economizar horas toda semana.

No **pdfcanada.ca**, construímos a ferramenta de **OCR de fatura** mais privada do mundo. Enquanto a maioria dos serviços envia seus documentos financeiros sensíveis para servidores na nuvem, nossa ferramenta processa tudo diretamente no seu navegador. Isso significa que seus dados financeiros nunca saem do seu dispositivo, mantendo você em conformidade e seguro.

Neste guia, mostraremos como usar nosso **scanner gratuito de faturas** para extrair dados para Excel, CSV ou para sua área de transferência instantaneamente.`,

        sections: [
            {
                id: "what-is-ocr",
                title: "O que é OCR de Fatura?",
                content: `**OCR (Reconhecimento Óptico de Caracteres)** para faturas é uma tecnologia que "lê" o texto dentro de seus arquivos PDF ou de imagem. Ele não vê apenas uma imagem; ele entende o que é um **Nome do Fornecedor**, o que é um **ID da Fatura** e qual número é o **Valor Total Devido**.

Nossa ferramenta usa uma abordagem híbrida:
1.  **Extração de Texto:** Se seu PDF foi gerado por software (como QuickBooks ou Xero), extraímos o texto diretamente com 100% de precisão.
2.  **OCR Tesseract:** Se seu PDF for um documento em papel digitalizado, usamos **Tesseract.js** para realizar o reconhecimento de caracteres baseado em IA localmente em sua máquina.

### Como Funciona a Tecnologia OCR
O **processamento de faturas** tradicional exigia entrada manual de dados—ler cada campo e digitá-lo em planilhas. O OCR moderno automatiza isso:
- **Reconhecimento de Padrões**: A IA identifica layouts típicos de faturas e posições de campos
- **Processamento de Linguagem Natural**: Entende o contexto ("Fatura #" vs "Total Devido")
- **Validação de Dados**: Verifica se as datas são válidas e se os valores incluem decimais corretamente
- **Suporte Multi-Formato**: Funciona com faturas padrão, recibos, contas e extratos`
            },
            {
                id: "how-to",
                title: "Como Converter Fatura PDF para Excel Grátis",
                content: `Usar nossa ferramenta de **extração de dados de fatura** é simples. Siga estes passos:

### Passo 1: Envie Sua Fatura
Navegue até nossa [Ferramenta de OCR de Fatura](/${lang}/invoice-ocr). Clique em 'Selecionar Arquivo' ou arraste seu PDF de fatura para o navegador. Suportamos:
- PDFs gerados por software (QuickBooks, FreshBooks, Xero, Wave)
- Faturas em papel digitalizadas
- Recibos fotografados de dispositivos móveis
- Anexos de fatura por e-mail (encaminhados como PDF)

### Passo 2: Digitalização Automática
Nosso motor digitalizará automaticamente o documento. Ele procura por campos-chave:
*   **Nome do Fornecedor:** A empresa que enviou a conta
*   **Endereço do Fornecedor:** Localização comercial para registros fiscais
*   **Número/ID da Fatura:** O código de referência único
*   **Data da Fatura:** Quando a fatura foi emitida
*   **Data de Vencimento:** Prazo de pagamento
*   **Valor Total:** O saldo final incluindo impostos
*   **Valor do Imposto:** GST/HST/PST/QST para faturas canadenses
*   **Subtotal:** Valor antes dos impostos
*   **Itens de Linha:** Produtos ou serviços individuais (onde disponível)

### Passo 3: Verifique e Edite
Revise os dados extraídos no formulário à direita. Nosso OCR atinge 95%+ de precisão em PDFs limpos, mas você deve sempre verificar:
- **Valores**: Garanta que os pontos decimais estejam corretos ($1.234,56 não $123.456)
- **Datas**: Verifique se o formato mês/dia/ano corresponde às suas configurações regionais
- **Nomes de Fornecedores**: Corrija erros de OCR nos nomes das empresas para consistência
- **Números de Faturas**: Códigos alfanuméricos às vezes podem ser mal lidos

### Passo 4: Exporte para Excel ou CSV
Clique em **Exportar para Excel** para baixar um arquivo .xlsx formatado com:
- Colunas de data formatadas corretamente (compatível com Excel)
- Formatação de moeda com símbolos de $
- Cabeçalhos para cada campo (Fornecedor, Data, Valor, etc.)
- Pronto para importar no QuickBooks, Xero, FreshBooks ou tabelas dinâmicas do Excel

Alternativamente, clique em **Copiar Dados** para colar diretamente em:
- Software de contabilidade (QuickBooks Desktop, Sage)
- Aplicativos de rastreamento de despesas (Expensify, Concur)
- Google Sheets ou Excel
- Bancos de dados personalizados ou sistemas ERP`
            },
            {
                id: "use-cases",
                title: "Casos de Uso Comuns de OCR de Fatura",
                content: `### Contabilidade de Pequenas Empresas
**Processamento Mensal de Despesas**
- Processe 20-50 faturas de fornecedores mensalmente sem digitação manual
- Extraia contas de serviços públicos, faturas de fornecedores e taxas de serviço
- Crie relatórios de despesas mensais em Excel para contadores
- Rastreie créditos fiscais de GST/HST automaticamente

**Preparação Fiscal de Fim de Ano**
- Digitalize todas as despesas comerciais para declaração de impostos da CRA
- Crie planilhas categorizadas para formulários T2125 ou T2
- Comprove deduções com dados de faturas organizados e pesquisáveis
- Reduza o risco de auditoria com registros precisos e verificáveis

### Fluxos de Trabalho de Freelancers e Contratados
**Gestão de Faturas de Clientes**
- Rastreie pagamentos recebidos de clientes
- Crie relatórios de envelhecimento de faturas (30/60/90 dias de atraso)
- Exporte para Excel para previsão de fluxo de caixa
- Integre com FreshBooks ou Wave Accounting

**Reembolso de Despesas**
- Digitalize recibos de refeições de negócios, viagens, equipamentos
- Extraia valores para pedidos de reembolso
- Crie relatórios de despesas para clientes ou empregadores
- Armazene cópias digitais em vez de recibos em papel`
            },
            {
                id: "accuracy",
                title: "Maximizando a Precisão do OCR",
                content: `### Dicas para Melhores Resultados
**Digitalizações de Alta Qualidade**
- **300 DPI ou superior**: Essencial para reconhecimento de texto pequeno
- **Alinhamento reto**: Corte e gire faturas para ficarem perfeitamente verticais
- **Boa iluminação**: Evite sombras, brilho ou manchas escuras em documentos digitalizados
- **Contraste**: Texto preto sobre fundo branco funciona melhor (evite papel colorido)

**Otimização do Formato de Arquivo**
- **PDFs de software**: Quase 100% de precisão (PDFs do QuickBooks, Xero)
- **Digitalizações limpas**: 95%+ de precisão em faturas impressas claramente
- **Fotos de celular**: 80-90% de precisão (use apps de scanner como Adobe Scan para melhores resultados)

### Erros Comuns de OCR e Como Corrigi-los
**Confusão de Números**
- "0" (zero) vs "O" (letra O): Revise os valores cuidadosamente
- "1" (um) vs "l" (L minúsculo) vs "I" (i maiúsculo): Verifique números de fatura
- "5" vs "S", "8" vs "B": Verifique totais e datas

**Problemas de Formato de Data**
- MM/DD/AAAA vs DD/MM/AAAA: Faturas canadenses frequentemente usam formato dia primeiro
- Datas curtas ("15/01/25"): Verifique o século (2025 vs 1925)

**Símbolos de Moeda**
- $ USD vs $ CAD: O OCR vê o símbolo, mas não a moeda—adicione manualmente se necessário
- Formatos europeus (€1.234,56): Decimal vs vírgula pode inverter`
            },
            {
                id: "privacy",
                title: "Por Que a Privacidade Importa para Documentos Financeiros",
                content: `Faturas contêm informações sensíveis: endereços, detalhes bancários e histórico de compras. Ao usar um **scanner de fatura online** genérico, você frequentemente dá permissão para armazenar e potencialmente analisar seus dados.

**A Diferença do pdfcanada.ca:**
*   **Sem Uploads:** Seus arquivos ficam na RAM do seu navegador
*   **Processamento Local:** A IA roda na *sua* CPU, não no nosso servidor
*   **Conformidade PIPEDA/GDPR:** Como não coletamos dados, somos a escolha mais segura para conformidade empresarial

### Riscos de Privacidade Financeira
**O Que Serviços de OCR na Nuvem Fazem com Seus Dados**
- Armazenam faturas em seus servidores (às vezes permanentemente)
- Analisam padrões de compra para fins de marketing
- Compartilham nomes de fornecedores com corretores de dados
- Usam dados de faturas para treinar modelos de IA (seus dados se tornam o produto deles)

**O Processamento Local Protege Você**
- **Segredos Comerciais**: Nomes de fornecedores e preços permanecem privados
- **Confidencialidade do Cliente**: Faturas de serviços profissionais (jurídicos, médicos) permanecem seguras
- **Inteligência Competitiva**: Impeça concorrentes de analisar seus padrões de gastos
- **Conformidade Regulatória**: PIPEDA (Canadá), GDPR (UE) exigem manuseio rigoroso de dados`
            },
            {
                id: "integration",
                title: "Integrando com Software de Contabilidade",
                content: `### Fluxos de Integração Direta
**QuickBooks Desktop/Online**
1. Exporte dados da fatura para Excel de nossa ferramenta OCR
2. Abra o QuickBooks e vá para Arquivo → Utilitários → Importar → Arquivos Excel
3. Mapeie colunas (Fornecedor → Nome, Valor → Total, Data → Data)
4. Revise e confirme a importação
5. O QuickBooks cria entradas de conta automaticamente

**Usuários Avançados de Excel**
**Tabelas Dinâmicas para Análise**
- Exporte 6 meses de faturas para um arquivo Excel
- Crie tabela dinâmica com Fornecedor nas linhas, Mês nas colunas, Soma do Valor como valores
- Identifique tendências de gastos, variações sazonais e concentração de fornecedores

**Formatação Condicional**
- Destaque faturas vencidas (Data + 30 dias < HOJE())
- Sinalize grandes valores (>$5.000) para revisão de aprovação`
            },
            {
                id: "benefits",
                title: "Benefícios de Usar um Scanner Automatizado de Faturas",
                content: `### Economia de Tempo e Eficiência
*   **Poupe Tempo:** Extraia 10 campos em 2 segundos em vez de digitar por 2 minutos (60x mais rápido)
*   **Processamento em Lote:** Lide com 50 faturas rapidamente
*   **Multi-Dispositivo:** Processe faturas do desktop, laptop, tablet ou celular

### Precisão e Redução de Erros
*   **Elimine Erros de Digitação:** A IA não cansa e troca "0" por "8"
*   **Formatação Consistente:** Datas sempre em AAAA-MM-DD, valores sempre com 2 decimais
*   **Regras de Validação:** O OCR sinaliza valores suspeitos

### Economia de Custo
*   **Custo Zero:** Obtenha recursos de **software de extração de faturas** de nível profissional por $0
*   **Sem Taxas por Fatura:** Diferente de serviços em nuvem cobrando $0,10-0,50 por fatura
*   **Volume Ilimitado:** Processe 10 ou 10.000 faturas—mesmo preço $0`
            },
            {
                id: "troubleshooting",
                title: "Solução de Problemas de OCR",
                content: `### Fatura Não Envia ou Digitaliza
**Problemas de Formato de Arquivo**
- Certifique-se de que o arquivo é realmente um PDF
- Converta imagens JPG/PNG para PDF primeiro
- Verifique o tamanho do arquivo—PDFs muito grandes (50+ MB) podem precisar de compressão

**Compatibilidade do Navegador**
- Use o Chrome, Firefox, Edge ou Safari mais recente
- Habilite o JavaScript (necessário para processamento OCR)

### Baixa Precisão de Extração
**Problemas de Qualidade de Digitalização**
- Digitalize novamente em DPI mais alto (300+ recomendado)
- Achate faturas amassadas antes de digitalizar
- Use aplicativo de scanner (Adobe Scan, Microsoft Lens) em vez da câmera do telefone

**Erros de Validação de Dados**
**Valores Suspeitos**
- $1234 vs $12,34: Ponto decimal ausente—revise qualquer valor abaixo de $100
- $10.000,00 vs $1.000,00: Erros de zero extra—verifique grandes valores`
            }
        ],

        faq: [
            {
                q: "O OCR de fatura é realmente grátis?",
                a: "Sim! Como todas as ferramentas no pdfcanada.ca, o conversor de fatura para excel é 100% gratuito, sem limites, sem marcas d'água e sem taxas ocultas."
            },
            {
                q: "Vocês suportam faturas digitalizadas/manuscritas?",
                a: "Suportamos todos os PDFs digitalizados usando OCR. Faturas impressas limpas atingem 95%+ de precisão. Notas manuscritas são mais difíceis (60-70% de precisão), mas nossa IA tentará a extração. Sempre verifique resultados manuscritos."
            },
            {
                q: "Posso extrair múltiplas faturas de uma vez?",
                a: "Atualmente, processamos uma fatura por vez para garantir a maior precisão. Você pode processar faturas sequencialmente e exportar para o mesmo arquivo Excel."
            },
            {
                q: "Quais formatos de arquivo posso enviar?",
                a: "Suportamos exclusivamente arquivos PDF. Para imagens JPG, PNG ou HEIC, converta-as para PDF primeiro usando nossa ferramenta de imagem para PDF."
            },
            {
                q: "Quão precisa é a extração OCR?",
                a: "A precisão depende da qualidade da fatura: PDFs gerados por software atingem quase 100%. Digitalizações limpas chegam a 95%+. Fotos de celular são 80-90% precisas. Sempre verifique os dados extraídos."
            },
            {
                q: "Posso exportar para o QuickBooks diretamente?",
                a: "Exporte para Excel primeiro, depois importe o arquivo Excel no QuickBooks usando Arquivo → Utilitários → Importar → Arquivos Excel."
            },
            {
                q: "A ferramenta armazena meus dados de fatura?",
                a: "Não. Todo o processamento OCR acontece localmente no seu navegador usando JavaScript. Sua fatura nunca é enviada para nossos servidores."
            },
            {
                q: "Como lidar com faturas em moeda estrangeira?",
                a: "O OCR detecta símbolos de moeda ($, €, £, ¥) mas não converte moedas. Se seu fornecedor cobra em USD e você precisa em CAD, converta manualmente antes de entrar no software de contabilidade."
            },
            {
                q: "A ferramenta funciona em dispositivos móveis?",
                a: "Sim! Use o Safari no iPhone/iPad ou Chrome no Android. A ferramenta se adapta a telas menores."
            },
            {
                q: "Posso extrair itens de linha (produtos/serviços individuais)?",
                a: "Nossa ferramenta extrai valores totais com alta precisão. A extração de itens de linha é experimental e pode não funcionar para todos os formatos de fatura. Foque nos totais para resultados mais confiáveis."
            },
            {
                q: "O que fazer se o OCR não encontrar um campo?",
                a: "Se o OCR deixar um campo em branco, digite manualmente os dados no formulário antes de exportar. Os dados editados serão exportados para o Excel."
            },
            {
                q: "Posso exportar para CSV em vez de Excel?",
                a: "Atualmente, exportamos para Excel (.xlsx) por padrão. Para obter CSV, abra o arquivo Excel exportado e use 'Salvar Como → CSV'."
            },
            {
                q: "Como verificar a precisão do OCR?",
                a: "Sempre verifique os valores extraídos em relação ao PDF original. Procure por: colocação do ponto decimal, formato da data e ortografia do nome do fornecedor."
            },
            {
                q: "Posso usar isso para preparação fiscal (CRA)?",
                a: "Sim! Exporte todas as despesas comerciais para o Excel, categorize e forneça a planilha ao seu contador. Mantenha as faturas originais para auditoria da CRA."
            },
            {
                q: "E se minha fatura estiver em francês?",
                a: "O OCR lida bem com faturas em francês. Rótulos de campos como 'Numéro de facture', 'Date', 'Montant total' são reconhecidos."
            }
        ],

        ctaTitle: "Pare de Digitar, Comece a Digitalizar.",
        ctaButton: "Testar OCR de Fatura Agora",
        ctaSubtext: "Extraia dados para Excel em segundos. 100% Privado."
    }
});

export const InvoiceOcrGuide: React.FC<GuideProps> = ({ lang }) => {
    const guideContent = getGuideContent(lang);
    const t = guideContent[lang as keyof typeof guideContent] || guideContent.en;

    const schema = {
        "@context": "https://schema.org",
        "@type": "SoftwareApplication",
        "name": t.h1,
        "operatingSystem": "All",
        "applicationCategory": "BusinessApplication",
        "offers": {
            "@type": "Offer",
            "price": "0",
            "priceCurrency": "USD"
        }
    };

    return (
        <div className="bg-white dark:bg-gray-950">
            <SEO
                title={t.seo.title}
                description={t.seo.desc}
                canonicalPath="/guides/invoice-ocr"
                faqs={t.faq}
                lang={lang}
                schema={schema}
                quickAnswer={{
                    question: lang === 'fr' ? "Comment convertir un PDF facture en Excel gratuitement ?" : "How to convert PDF invoice to Excel for free?",
                    answer: lang === 'fr'
                        ? "Utilisez l'outil OCR de pdfcanada.ca. Glissez votre facture, laissez l'IA extraire les données et téléchargez le fichier Excel. Tout se passe localement dans votre navigateur."
                        : "Use pdfcanada.ca's OCR tool. Drag your invoice, let the AI extract the data, and download the Excel file. Everything happens locally in your browser.",
                    tool: "Invoice OCR Tool",
                    steps: lang === 'fr'
                        ? ["Importez la facture", "Vérifiez les données", "Exportez en Excel"]
                        : ["Upload Invoice", "Verify Data", "Export to Excel"],
                }}
                breadcrumbs={[
                    { name: lang === 'fr' ? 'Accueil' : (lang === 'pt' ? 'Início' : 'Home'), path: lang === 'en' ? '/' : `/${lang}` },
                    { name: lang === 'fr' ? 'Guides' : (lang === 'pt' ? 'Guias' : 'Guides'), path: lang === 'fr' ? '/fr/guides/ultimate-pdf-guide' : (lang === 'pt' ? '/pt/guides/ultimate-pdf-guide' : '/guides/ultimate-pdf-guide') },
                    { name: lang === 'fr' ? 'OCR Factures' : (lang === 'pt' ? 'OCR Faturas' : 'Invoice OCR'), path: lang === 'fr' ? '/fr/guides/invoice-ocr' : (lang === 'pt' ? '/pt/guides/invoice-ocr' : '/guides/invoice-ocr') }
                ]}
            />
            <PageLayout
                title={t.h1}
                subtitle={t.subtitle}
                icon={<Scan size={32} />}
                breadcrumbs={[
                    { name: lang === 'fr' ? 'Accueil' : (lang === 'pt' ? 'Início' : 'Home'), href: lang === 'en' ? '/' : `/${lang}` },
                    { name: lang === 'fr' ? 'Guides' : (lang === 'pt' ? 'Guias' : 'Guides'), href: lang === 'fr' ? '/fr/guides/ultimate-pdf-guide' : (lang === 'pt' ? '/pt/guides/ultimate-pdf-guide' : '/guides/ultimate-pdf-guide') },
                    { name: lang === 'fr' ? 'OCR Factures' : (lang === 'pt' ? 'OCR Faturas' : 'Invoice OCR'), href: '#' }
                ]}
            >
                <div className="w-full space-y-8 sm:space-y-12 md:space-y-16">
                    <ToolPromo tool="invoice-ocr" lang={lang} />
                    <div className="text-base sm:text-lg md:text-xl leading-relaxed text-gray-600 dark:text-gray-400 mb-12 sm:mb-14 md:mb-16">
                        <MarkdownContent content={t.intro} />
                    </div>

                    {/* Features Tiles */}
                    <div className="grid grid-cols-1 sm:grid-cols-2 md:grid-cols-3 gap-4 sm:gap-6 md:gap-8 mb-16 sm:mb-18 md:mb-20">
                        <div className="p-6 sm:p-8 bg-gray-50 dark:bg-gray-900 rounded-xl sm:rounded-2xl md:rounded-[2rem] border border-gray-100 dark:border-gray-800 shadow-sm">
                            <FileSpreadsheet className="text-canada-red mb-3 sm:mb-4" size={28} />
                            <h3 className="text-lg sm:text-xl font-bold mb-2">{lang === 'fr' ? "Export Excel" : "Export to Excel"}</h3>
                            <p className="text-sm sm:text-base text-gray-500">{lang === 'fr' ? "Téléchargez vos données en format .xlsx instantanément." : "Download your data in .xlsx format instantly."}</p>
                        </div>
                        <div className="p-6 sm:p-8 bg-gray-50 dark:bg-gray-900 rounded-xl sm:rounded-2xl md:rounded-[2rem] border border-gray-100 dark:border-gray-800 shadow-sm">
                            <Database className="text-canada-red mb-3 sm:mb-4" size={28} />
                            <h3 className="text-lg sm:text-xl font-bold mb-2">{lang === 'fr' ? "IA Locale" : "Local AI"}</h3>
                            <p className="text-sm sm:text-base text-gray-500">{lang === 'fr' ? "Extraction intelligente sans serveur." : "Smart extraction without any servers."}</p>
                        </div>
                        <div className="p-6 sm:p-8 bg-gray-50 dark:bg-gray-900 rounded-xl sm:rounded-2xl md:rounded-[2rem] border border-gray-100 dark:border-gray-800 shadow-sm">
                            <Lock className="text-canada-red mb-3 sm:mb-4" size={28} />
                            <h3 className="text-lg sm:text-xl font-bold mb-2">{lang === 'fr' ? "Zéro Risque" : "Zero Risk"}</h3>
                            <p className="text-sm sm:text-base text-gray-500">{lang === 'fr' ? "Vos finances restent totalement privées." : "Your finances stay completely private."}</p>
                        </div>
                    </div>

                    {/* Content Sections */}
                    <div className="space-y-8 sm:space-y-12 md:space-y-16">
                        {t.sections.map((section: any) => (
                            <section key={section.id} id={section.id} className="scroll-mt-20 sm:scroll-mt-24">
                                <h2 className="text-2xl sm:text-3xl font-black mb-4 sm:mb-6 flex items-center gap-2 sm:gap-3">
                                    <div className="w-1.5 sm:w-2 h-6 sm:h-8 bg-canada-red rounded-full" />
                                    {section.title}
                                </h2>
                                <div className="prose prose-base md:prose-lg lg:prose-xl dark:prose-invert max-w-none text-gray-600 dark:text-gray-400">
                                    <MarkdownContent content={section.content} />
                                </div>
                            </section>
                        ))}
                    </div>

                    {/* FAQ */}
                    <div className="my-16 sm:my-18 md:my-20">
                        <div className="flex items-center gap-2 sm:gap-3 mb-8 sm:mb-10">
                            <Info className="text-canada-red" size={28} />
                            <h2 className="text-2xl sm:text-3xl font-black text-gray-900 dark:text-white">FAQ</h2>
                        </div>
                        <div className="grid gap-4 sm:gap-5 md:gap-6">
                            {t.faq.map((item: any, i: number) => (
                                <div key={i} className="p-4 sm:p-6 md:p-8 bg-white dark:bg-gray-900 rounded-2xl sm:rounded-3xl border border-gray-100 dark:border-gray-800 shadow-sm group hover:border-canada-red/30 transition-colors">
                                    <h4 className="text-base sm:text-lg md:text-xl font-bold mb-3 sm:mb-4 text-gray-900 dark:text-white group-hover:text-canada-red transition-colors">
                                        {item.q}
                                    </h4>
                                    <div className="text-sm sm:text-base md:text-lg text-gray-600 dark:text-gray-400 leading-relaxed">
                                        {item.a}
                                    </div>
                                </div>
                            ))}
                        </div>
                    </div>

                    {/* CTA */}
                    <div className="mt-16 sm:mt-18 md:mt-20 bg-canada-red p-6 sm:p-8 md:p-10 lg:p-12 rounded-2xl sm:rounded-[2rem] md:rounded-[2.5rem] lg:rounded-[3rem] text-center text-white shadow-2xl shadow-red-500/20">
                        <h2 className="text-2xl sm:text-3xl md:text-4xl font-black mb-4 sm:mb-6 leading-tight">{t.ctaTitle}</h2>
                        <p className="text-base sm:text-lg md:text-xl mb-8 sm:mb-10 opacity-90">{t.ctaSubtext}</p>
                        <Link href={`/${lang}/invoice-ocr`}
                            className="inline-block bg-white text-canada-red px-6 py-3 sm:px-8 sm:py-4 md:px-10 md:py-4 lg:px-12 rounded-full font-black text-base sm:text-lg md:text-xl hover:scale-105 transition-all shadow-lg active:scale-95"
                        >
                            {t.ctaButton}
                        </Link>
                    </div>

                    <AISnapshot
                        question={lang === 'fr' ? "Comment convertir un PDF facture en Excel ?" : "How to convert PDF invoice to Excel?"}
                        answer={lang === 'fr'
                            ? "Utilisez l'outil OCR de pdfcanada.ca pour extraire automatiquement les données de vos factures et les exporter vers un fichier Excel, le tout localement."
                            : "Use pdfcanada.ca's OCR tool to automatically extract data from your invoices and export them to an Excel file, all locally."}
                        toolName="Invoice OCR Tool"
                        steps={lang === 'fr'
                            ? ["Sélectionnez le fichier", "Vérifiez l'extraction", "Téléchargez l'Excel"]
                            : ["Select File", "Verify Extraction", "Download Excel"]}
                        lang={lang}
                    />

                    <RelatedTools lang={lang} currentPath="/guides/invoice-ocr" />

                    <div className="mt-12 p-6 bg-gray-50 dark:bg-gray-800/50 rounded-2xl border border-gray-100 dark:border-gray-700">
                        <h3 className="text-lg font-bold mb-4 flex items-center gap-2">
                            {lang === 'fr' ? 'Voir Aussi' : (lang === 'pt' ? 'Veja Também' : 'Also See')}
                        </h3>
                        <div className="flex flex-wrap gap-4">
                            <Link href={`/${lang}/guides/pdf-to-csv`} className="flex items-center gap-2 px-4 py-2 bg-white dark:bg-gray-900 rounded-lg shadow-sm hover:shadow-md transition-shadow text-sm font-medium text-gray-700 dark:text-gray-300">
                                <ArrowRight size={16} className="text-canada-red" />
                                {lang === 'fr' ? 'Guide PDF vers CSV' : (lang === 'pt' ? 'Guia PDF para CSV' : 'PDF to CSV Guide')}
                            </Link>
                            <Link href={`/${lang}/guides/pdf-to-excel`} className="flex items-center gap-2 px-4 py-2 bg-white dark:bg-gray-900 rounded-lg shadow-sm hover:shadow-md transition-shadow text-sm font-medium text-gray-700 dark:text-gray-300">
                                <ArrowRight size={16} className="text-canada-red" />
                                {lang === 'fr' ? 'Guide PDF vers Excel' : (lang === 'pt' ? 'Guia PDF para Excel' : 'PDF to Excel Guide')}
                            </Link>
                            <Link href={`/${lang}/guides/analyze-pdf`} className="flex items-center gap-2 px-4 py-2 bg-white dark:bg-gray-900 rounded-lg shadow-sm hover:shadow-md transition-shadow text-sm font-medium text-gray-700 dark:text-gray-300">
                                <ArrowRight size={16} className="text-canada-red" />
                                {lang === 'fr' ? 'Guide Analyser PDF' : (lang === 'pt' ? 'Guia Analisar PDF' : 'Analyze PDF Guide')}
                            </Link>
                            <Link href={`/${lang}/guides/finance-pdf-security`} className="flex items-center gap-2 px-4 py-2 bg-white dark:bg-gray-900 rounded-lg shadow-sm hover:shadow-md transition-shadow text-sm font-medium text-gray-700 dark:text-gray-300">
                                <ArrowRight size={16} className="text-canada-red" />
                                {lang === 'fr' ? 'Guide Sécurité PDF Finance' : (lang === 'pt' ? 'Guia Segurança PDF Finanças' : 'Finance PDF Security Guide')}
                            </Link>
                        </div>
                    </div>

                    <AuthorBio lang={lang} />
                </div>
            </PageLayout>
        </div>
    );
};
