'use client';

import Link from 'next/link';
import React from 'react';
import { Scan, Shield, Zap, CheckCircle, Info, ArrowRight, FileSpreadsheet, FileText, Database, Lock, Search } from 'lucide-react';
import { Language, CURRENT_YEAR } from '../../../utils/i18n';
import { SEO } from '../../SEO';
import { PageLayout } from '../../PageLayout';
import { AuthorBio } from '../../AuthorBio';
import { RelatedTools } from '../../RelatedTools';
import { AISnapshot } from '../../AISnapshot';
import { MarkdownContent } from '../../MarkdownContent';

interface GuideProps {
    lang: Language;
}

const getGuideContent = (lang: Language) => ({
    en: {
        seo: {
            title: `Free PDF Invoice to Excel Converter | OCR Scanner ${CURRENT_YEAR} | pdfcanada.ca`,
            desc: `Convert PDF invoices to Excel/CSV for free. Our AI-powered OCR scanner extracts dates, amounts, and vendor names locally. No uploads, 100% private & secure.`
        },
        h1: `Free PDF Invoice to Excel Converter (${CURRENT_YEAR})`,
        subtitle: "The complete guide to automated invoice data extraction using private, local OCR technology.",

        intro: `Tired of manually typing data from PDF invoices into spreadsheets? You're not alone. Manual data entry is slow, prone to errors, and frankly, a waste of your valuable time. Whether you're a freelancer managing expenses or a small business owner handling dozens of bills, a reliable **PDF invoice to Excel converter** can save you hours every week.

At **pdfcanada.ca**, we've built the world's most private **invoice OCR** tool. While most services upload your sensitive financial documents to their servers, our tool processes everything right in your browser. This means your financial data never leaves your device, keeping you compliant and secure.

In this guide, we'll show you how to use our **free invoice scanner** to extract data into Excel, CSV, or your clipboard instantly.`,

        sections: [
            {
                id: "what-is-ocr",
                title: "What is Invoice OCR?",
                content: `**OCR (Optical Character Recognition)** for invoices is a technology that "reads" the text inside your PDF or image files. It doesn't just see a picture; it understands what is a **Vendor Name**, what is an **Invoice ID**, and which number is the **Total Amount Due**.

Our tool uses a hybrid approach:
1.  **Text Extraction:** If your PDF was generated by software (like QuickBooks or Xero), we extract the text directly for 100% accuracy.
2.  **Tesseract OCR:** If your PDF is a scanned paper document, we use **Tesseract.js** to perform AI-based character recognition locally on your machine.`
            },
            {
                id: "how-to",
                title: "How to Convert PDF Invoice to Excel for Free",
                content: `Using our **invoice data extraction** tool is straightforward. Follow these steps:

### Step 1: Upload Your Invoice
Navigate to our [Invoice OCR Tool](/${lang}/invoice-ocr). Click 'Select File' or drag your invoice PDF into the browser. 

### Step 2: Automated Scanning
Our engine will automatically scan the document. It looks for four key fields:
*   **Vendor Name:** The company that sent the bill.
*   **Invoice Number/ID:** The unique reference code.
*   **Date:** When the invoice was issued.
*   **Total Amount:** The final balance including taxes.

### Step 3: Verify and Edit
Review the extracted data in the form on the right. If the OCR missed a character (common with handwritten or blurry scans), you can edit the fields directly.

### Step 4: Export to Excel or CSV
Click **Export to Excel** to download a formatted .xlsx file, or **Copy Data** to paste it directly into your accounting software.`
            },
            {
                id: "privacy",
                title: "Why Privacy Matters for Financial Documents",
                content: `Invoices contain sensitive information: addresses, bank details, and purchase history. When you use a generic **online invoice scanner**, you are often giving that company permission to store and potentially analyze your data.

**The pdfcanada.ca Difference:**
*   **No Uploads:** Your files stay in your browser RAM.
*   **Local Processing:** The AI runs on *your* CPU, not our server.
*   **PIPEDA/GDPR Compliant:** Since we don't collect data, we are the safest choice for business compliance.`
            },
            {
                id: "benefits",
                title: "Benefits of Using an Automated Invoice Scanner",
                content: `*   **Save Time:** Extract 10 fields in 2 seconds instead of typing for 2 minutes.
*   **Eliminate Typos:** AI doesn't get tired and swap "0" for "8".
*   **Better Organization:** Exporting to Excel makes it easy to search your historical expenses.
*   **Zero Cost:** Get professional-grade **invoice extraction software** features for $0.`
            }
        ],

        faq: [
            {
                q: "Is the invoice OCR really free?",
                a: "Yes! Like all tools on pdfcanada.ca, the **invoice to excel converter** is 100% free with no limits and no watermarks."
            },
            {
                q: "Do you support scanned/handwritten invoices?",
                a: "We support all scanned PDFs using OCR. Handwritten notes are more difficult, but as long as the text is legible, our AI scanner will attempt to extract it."
            },
            {
                q: "Can I extract multiple invoices at once?",
                a: "Currently, we process one invoice at a time to ensure the highest accuracy. You can 'Scan Another' immediately after exporting your data."
            },
            {
                q: "Which file formats can I upload?",
                a: "We primary support PDF files. For the best **invoice OCR** results, ensure your PDF is clear and well-lit if it was a photo scan."
            }
        ],

        ctaTitle: "Stop Typing, Start Scanning.",
        ctaButton: "Try Invoice OCR Now",
        ctaSubtext: "Extract data to Excel in seconds. 100% Private."
    },
    fr: {
        seo: {
            title: `Convertisseur Facture PDF vers Excel Gratuit | Scanner OCR ${CURRENT_YEAR} | pdfcanada.ca`,
            desc: `Convertissez vos factures PDF en Excel/CSV gratuitement. Notre scanner OCR intelligent extrait les dates, montants et noms de vendeurs localement. 100% privé.`
        },
        h1: `Convertisseur de Facture PDF vers Excel Gratuit (${CURRENT_YEAR})`,
        subtitle: "Le guide complet de l'extraction automatisée des données de facturation par OCR local et privé.",

        intro: `Fatigué de saisir manuellement les données de vos factures PDF dans des feuilles de calcul ? La saisie manuelle est lente, source d'erreurs et constitue une perte de temps précieuse. Que vous soyez un travailleur autonome ou un propriétaire de petite entreprise, un bon outil de **conversion de facture PDF en Excel** peut vous faire gagner des heures chaque semaine.

Chez **pdfcanada.ca**, nous avons conçu l'outil d'**OCR de factures** le plus privé au monde. Contrairement aux autres services, notre outil traite tout directement dans votre navigateur. Vos données financières ne quittent jamais votre appareil.

Dans ce guide, nous vous montrerons comment utiliser notre **scanner de factures gratuit** pour extraire vos données vers Excel, CSV ou votre presse-papiers instantanément.`,

        sections: [
            {
                id: "what-is-ocr",
                title: "Qu'est-ce que l'OCR de facture ?",
                content: `L'**OCR (Reconnaissance Optique de Caractères)** pour factures est une technologie qui « lit » le texte à l'intérieur de vos fichiers PDF. Elle ne voit pas seulement une image ; elle comprend ce qu'est un **Nom de Vendeur**, un **Numéro de Facture** et un **Montant Total**.

Notre outil utilise une approche hybride :
1.  **Extraction de texte :** Pour les PDF générés par logiciel (comme QuickBooks).
2.  **OCR Tesseract :** Pour les documents papier scannés, utilisant l'IA localement sur votre machine.`
            },
            {
                id: "how-to",
                title: "Comment convertir une facture PDF en Excel gratuitement",
                content: `Utiliser notre outil d'**extraction de données de facture** est simple :

### Étape 1 : Téléversez votre facture
Allez sur notre [Outil OCR Factures](/${lang}/invoice-ocr).

### Étape 2 : Analyse automatisée
Notre moteur scanne automatiquement le document pour trouver :
*   **Vendeur :** L'entreprise qui a envoyé la facture.
*   **Numéro de facture :** Le code de référence.
*   **Date :** La date d'émission.
*   **Montant Total :** Le solde final TTC.

### Étape 3 : Vérifiez et modifiez
Révisez les données extraites. Vous pouvez modifier les champs directement si nécessaire.

### Étape 4 : Exportez vers Excel ou CSV
Cliquez sur **Exporter vers Excel** pour télécharger un fichier .xlsx, ou **Copier** pour coller les données ailleurs.`
            },
            {
                id: "privacy",
                title: "Pourquoi la confidentialité est cruciale",
                content: `Les factures contiennent des informations sensibles. Avec **pdfcanada.ca** :
*   **Aucun envoi :** Vos fichiers restent dans votre navigateur.
*   **Traitement local :** L'IA tourne sur *votre* processeur.
*   **Conformité :** La meilleure option pour respecter la vie privée de vos clients.`
            }
        ],

        faq: [
            {
                q: "Est-ce vraiment gratuit ?",
                a: "Oui ! Comme tous les outils sur pdfcanada.ca, l'**OCR de facture** est 100% gratuit, sans limites et sans filigranes."
            },
            {
                q: "Supportez-vous les factures écrites à la main ?",
                a: "Nous supportons les scans. Pour l'écriture manuscrite, le résultat dépend de la lisibilité, mais notre scanner tentera l'extraction."
            }
        ],

        ctaTitle: "Arrêtez de taper, commencez à scanner.",
        ctaButton: "Essayer l'OCR Facture",
        ctaSubtext: "Extrayez vos données en quelques secondes. 100% Privé."
    }
});

export const InvoiceOcrGuide: React.FC<GuideProps> = ({ lang }) => {
    const guideContent = getGuideContent(lang);
    const t = guideContent[lang] || guideContent.en;

    const schema = {
        "@context": "https://schema.org",
        "@type": "SoftwareApplication",
        "name": t.h1,
        "operatingSystem": "All",
        "applicationCategory": "BusinessApplication",
        "offers": {
            "@type": "Offer",
            "price": "0",
            "priceCurrency": "USD"
        }
    };

    return (
        <div className="bg-white dark:bg-gray-950">
            <SEO
                title={t.seo.title}
                description={t.seo.desc}
                canonicalPath="/guides/invoice-ocr"
                faqs={t.faq}
                lang={lang}
                schema={schema}
                quickAnswer={{
                    question: lang === 'fr' ? "Comment convertir un PDF facture en Excel gratuitement ?" : "How to convert PDF invoice to Excel for free?",
                    answer: lang === 'fr'
                        ? "Utilisez l'outil OCR de pdfcanada.ca. Glissez votre facture, laissez l'IA extraire les données et téléchargez le fichier Excel. Tout se passe localement dans votre navigateur."
                        : "Use pdfcanada.ca's OCR tool. Drag your invoice, let the AI extract the data, and download the Excel file. Everything happens locally in your browser.",
                    tool: "Invoice OCR Tool",
                    steps: lang === 'fr'
                        ? ["Importez la facture", "Vérifiez les données", "Exportez en Excel"]
                        : ["Upload Invoice", "Verify Data", "Export to Excel"],
                }}
                breadcrumbs={[
                    { name: lang === 'fr' ? 'Accueil' : 'Home', path: lang === 'fr' ? '/fr' : '/' },
                    { name: lang === 'fr' ? 'Guides' : 'Guides', path: lang === 'fr' ? '/fr/guides/ultimate-pdf-guide' : '/guides/ultimate-pdf-guide' },
                    { name: lang === 'fr' ? 'OCR Factures' : 'Invoice OCR', path: lang === 'fr' ? '/fr/guides/invoice-ocr' : '/guides/invoice-ocr' }
                ]}
            />
            <PageLayout
                title={t.h1}
                subtitle={t.subtitle}
                icon={<Scan size={32} />}
                breadcrumbs={[
                    { name: lang === 'fr' ? 'Accueil' : 'Home', href: lang === 'fr' ? '/fr' : '/' },
                    { name: lang === 'fr' ? 'Guides' : 'Guides', href: lang === 'fr' ? '/fr/guides/ultimate-pdf-guide' : '/guides/ultimate-pdf-guide' },
                    { name: lang === 'fr' ? 'OCR Factures' : 'Invoice OCR', href: '#' }
                ]}
            >
                <div className="max-w-4xl mx-auto py-8">
                    <div className="text-xl leading-relaxed text-gray-600 dark:text-gray-400 mb-16">
                        <MarkdownContent content={t.intro} />
                    </div>

                    {/* Features Tiles */}
                    <div className="grid md:grid-cols-3 gap-8 mb-20">
                        <div className="p-8 bg-gray-50 dark:bg-gray-900 rounded-[2rem] border border-gray-100 dark:border-gray-800 shadow-sm">
                            <FileSpreadsheet className="text-canada-red mb-4" size={32} />
                            <h3 className="text-xl font-bold mb-2">{lang === 'fr' ? "Export Excel" : "Export to Excel"}</h3>
                            <p className="text-gray-500">{lang === 'fr' ? "Téléchargez vos données en format .xlsx instantanément." : "Download your data in .xlsx format instantly."}</p>
                        </div>
                        <div className="p-8 bg-gray-50 dark:bg-gray-900 rounded-[2rem] border border-gray-100 dark:border-gray-800 shadow-sm">
                            <Database className="text-canada-red mb-4" size={32} />
                            <h3 className="text-xl font-bold mb-2">{lang === 'fr' ? "IA Locale" : "Local AI"}</h3>
                            <p className="text-gray-500">{lang === 'fr' ? "Extraction intelligente sans serveur." : "Smart extraction without any servers."}</p>
                        </div>
                        <div className="p-8 bg-gray-50 dark:bg-gray-900 rounded-[2rem] border border-gray-100 dark:border-gray-800 shadow-sm">
                            <Lock className="text-canada-red mb-4" size={32} />
                            <h3 className="text-xl font-bold mb-2">{lang === 'fr' ? "Zéro Risque" : "Zero Risk"}</h3>
                            <p className="text-gray-500">{lang === 'fr' ? "Vos finances restent totalement privées." : "Your finances stay completely private."}</p>
                        </div>
                    </div>

                    {/* Content Sections */}
                    <div className="space-y-16">
                        {t.sections.map((section: any) => (
                            <section key={section.id} id={section.id} className="scroll-mt-24">
                                <h2 className="text-3xl font-black mb-6 flex items-center gap-3">
                                    <div className="w-2 h-8 bg-canada-red rounded-full" />
                                    {section.title}
                                </h2>
                                <div className="prose prose-xl dark:prose-invert max-w-none text-gray-600 dark:text-gray-400">
                                    <MarkdownContent content={section.content} />
                                </div>
                            </section>
                        ))}
                    </div>

                    {/* FAQ */}
                    <div className="my-20">
                        <div className="flex items-center gap-3 mb-10">
                            <Info className="text-canada-red" size={32} />
                            <h2 className="text-3xl font-black text-gray-900 dark:text-white">FAQ</h2>
                        </div>
                        <div className="grid gap-6">
                            {t.faq.map((item: any, i: number) => (
                                <div key={i} className="p-8 bg-white dark:bg-gray-900 rounded-3xl border border-gray-100 dark:border-gray-800 shadow-sm group hover:border-canada-red/30 transition-colors">
                                    <h4 className="text-xl font-bold mb-4 text-gray-900 dark:text-white group-hover:text-canada-red transition-colors">
                                        {item.q}
                                    </h4>
                                    <div className="text-lg text-gray-600 dark:text-gray-400 leading-relaxed">
                                        {item.a}
                                    </div>
                                </div>
                            ))}
                        </div>
                    </div>

                    {/* CTA */}
                    <div className="mt-20 bg-canada-red p-8 md:p-12 rounded-[2.5rem] md:rounded-[3rem] text-center text-white shadow-2xl shadow-red-500/20">
                        <h2 className="text-3xl md:text-4xl font-black mb-6 leading-tight">{t.ctaTitle}</h2>
                        <p className="text-lg md:text-xl mb-10 opacity-90">{t.ctaSubtext}</p>
                        <Link href={`/${lang}/invoice-ocr`}
                            className="inline-block bg-white text-canada-red px-10 md:px-12 py-4 md:py-5 rounded-full font-black text-lg md:text-xl hover:scale-105 transition-all shadow-lg active:scale-95"
                        >
                            {t.ctaButton}
                        </Link>
                    </div>

                    <AISnapshot
                        question={lang === 'fr' ? "Comment convertir un PDF facture en Excel ?" : "How to convert PDF invoice to Excel?"}
                        answer={lang === 'fr'
                            ? "Utilisez l'outil OCR de pdfcanada.ca pour extraire automatiquement les données de vos factures et les exporter vers un fichier Excel, le tout localement."
                            : "Use pdfcanada.ca's OCR tool to automatically extract data from your invoices and export them to an Excel file, all locally."}
                        toolName="Invoice OCR Tool"
                        steps={lang === 'fr'
                            ? ["Sélectionnez le fichier", "Vérifiez l'extraction", "Téléchargez l'Excel"]
                            : ["Select File", "Verify Extraction", "Download Excel"]}
                        lang={lang}
                    />

                    <RelatedTools lang={lang} currentPath="/guides/invoice-ocr" />

                    <AuthorBio lang={lang} />
                </div>
            </PageLayout>
        </div>
    );
};
