
'use client';

import React from 'react';
import { FileText, ShieldCheck, Zap, HelpCircle, ArrowRight, NotebookIcon, Code2, Image as ImageIcon, FileCode } from 'lucide-react';
import { Language, translations } from '../../../utils/i18n';
import Link from 'next/link';

interface IpynbToPdfGuideProps {
    lang: Language;
}

export const IpynbToPdfGuide: React.FC<IpynbToPdfGuideProps> = ({ lang }) => {
    const t = translations[lang as keyof typeof translations];

    const sections = lang === 'en' ? [
        {
            title: "How to Convert IPYNB to PDF Locally",
            icon: <Zap className="w-6 h-6 text-orange-500" />,
            content: "Converting Jupyter Notebooks often requires complex server-side setups. Our tool simplifies this by doing everything in your browser.",
            steps: [
                "Select or drag & drop your .ipynb file into the converter.",
                "Wait a few seconds while we parse your cells and render the content.",
                "Review the preview (if available) and click 'Download PDF'.",
                "Your formatted notebook is saved directly to your device."
            ]
        },
        {
            title: "Supported Notebook Features",
            icon: <Code2 className="w-6 h-6 text-blue-500" />,
            content: "We focus on high-fidelity rendering of essential notebook components:",
            list: [
                "Markdown cells with basic formatting.",
                "Code cells with syntax awareness.",
                "Text outputs and tracebacks.",
                "Images (PNG/JPEG) generated by matplotlib or seaborn.",
                "Standard Jupyter Notebook v4 format."
            ]
        },
        {
            title: "Privacy First Conversion",
            icon: <ShieldCheck className="w-6 h-6 text-green-500" />,
            content: "Data scientists often work with sensitive data. That's why our converter is built with a strictly local architecture.",
            list: [
                "Zero data uploads: Your .ipynb stays on your machine.",
                "Confidential code: No one can see your logic or data structures.",
                "Secure environment: Operates within the browser sandbox."
            ]
        }
    ] : [
        {
            title: "Comment Convertir IPYNB en PDF Localement",
            icon: <Zap className="w-6 h-6 text-orange-500" />,
            content: "La conversion de Jupyter Notebooks nécessite souvent des configurations serveur complexes. Notre outil simplifie cela en faisant tout dans votre navigateur.",
            steps: [
                "Sélectionnez ou glissez-déposez votre fichier .ipynb dans le convertisseur.",
                "Attendez quelques secondes pendant que nous analysons vos cellules.",
                "Vérifiez l'aperçu et cliquez sur 'Télécharger le PDF'.",
                "Votre notebook formaté est enregistré directement sur votre appareil."
            ]
        },
        {
            title: "Fonctionnalités Supportées",
            icon: <Code2 className="w-6 h-6 text-blue-500" />,
            content: "Nous nous concentrons sur le rendu fidèle des composants essentiels du notebook :",
            list: [
                "Cellules Markdown avec formatage de base.",
                "Cellules de code avec coloration syntaxique.",
                "Sorties textuelles et traces d'erreurs.",
                "Images (PNG/JPEG) générées par matplotlib ou seaborn.",
                "Format standard Jupyter Notebook v4."
            ]
        },
        {
            title: "Conversion Privée par Défaut",
            icon: <ShieldCheck className="w-6 h-6 text-green-500" />,
            content: "Les scientifiques de données travaillent souvent avec des données sensibles. C'est pourquoi notre convertisseur est bâti sur une architecture strictement locale.",
            list: [
                "Zéro téléchargement : Votre .ipynb reste sur votre machine.",
                "Code confidentiel : Personne ne voit votre logique ou vos données.",
                "Environnement sécurisé : Fonctionne dans le bac à sable du navigateur."
            ]
        }
    ];

    const faqs = lang === 'en' ? [
        {
            q: "Do I need to install Python or Jupyter?",
            a: "No. This tool parses the .ipynb file structure directly. You don't need any local environment installed."
        },
        {
            q: "Are interactive widgets supported?",
            a: "Currently, interactive widgets (like ipywidgets) are not rendered in the static PDF. We focus on code, text, and flat images."
        },
        {
            q: "Does it support LaTeX math?",
            a: "Basic inline and block math provided by Jupyter is rendered as text. We are working on full LaTeX support."
        },
        {
            q: "What is the maximum file size?",
            a: "Since processing happens locally, it depends on your browser's memory. Most notebooks up to 50MB convert seamlessly."
        }
    ] : [
        {
            q: "Dois-je installer Python ou Jupyter ?",
            a: "Non. Cet outil analyse directement la structure du fichier .ipynb. Vous n'avez besoin d'aucun environnement local."
        },
        {
            q: "Les widgets interactifs sont-ils supportés ?",
            a: "Actuellement, les widgets interactifs ne sont pas rendus dans le PDF statique. Nous nous concentrons sur le code, le texte et les images."
        },
        {
            q: "Est-ce qu'il supporte les maths LaTeX ?",
            a: "Les mathématiques de base sont rendues sous forme de texte. Nous travaillons sur le support complet de LaTeX."
        },
        {
            q: "Quelle est la taille maximale des fichiers ?",
            a: "Comme le traitement est local, cela dépend de la mémoire de votre navigateur. La plupart des notebooks jusqu'à 50 Mo se convertissent sans problème."
        }
    ];

    return (
        <div className="max-w-4xl mx-auto px-6 py-12">
            <header className="text-center mb-16">
                <div className="inline-flex items-center justify-center w-20 h-20 rounded-3xl bg-orange-50 dark:bg-orange-500/10 mb-6 shadow-inner">
                    <NotebookIcon className="w-10 h-10 text-orange-600 dark:text-orange-400" />
                </div>
                <h1 className="text-4xl md:text-5xl font-black text-modern-neutral-900 dark:text-white mb-6 tracking-tight">
                    {lang === 'fr' ? 'Guide : IPYNB vers PDF' : 'The Ultimate IPYNB to PDF Guide'}
                </h1>
                <p className="text-xl text-modern-neutral-500 dark:text-modern-neutral-400 leading-relaxed max-w-2xl mx-auto">
                    {lang === 'fr'
                        ? 'Apprenez à convertir vos carnets Jupyter en documents PDF professionnels sans jamais quitter votre navigateur.'
                        : 'Learn how to transform your Jupyter Notebooks into professional PDF documents without ever leaving your browser.'}
                </p>
            </header>

            <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-8 mb-20">
                <div className="p-6 bg-white dark:bg-modern-neutral-900 rounded-3xl border border-modern-neutral-100 dark:border-modern-neutral-800 shadow-xl shadow-modern-neutral-100/50 dark:shadow-none">
                    <div className="w-12 h-12 rounded-2xl bg-orange-50 dark:bg-orange-500/10 flex items-center justify-center mb-4 text-orange-600 dark:text-orange-400">
                        <FileCode className="w-6 h-6" />
                    </div>
                    <h3 className="font-bold text-lg mb-2 dark:text-white">Clean Formatting</h3>
                    <p className="text-sm text-modern-neutral-500 dark:text-modern-neutral-400 leading-relaxed">Code blocks are styled with fixed-width fonts and distinct backgrounds for readability.</p>
                </div>
                <div className="p-6 bg-white dark:bg-modern-neutral-900 rounded-3xl border border-modern-neutral-100 dark:border-modern-neutral-800 shadow-xl shadow-modern-neutral-100/50 dark:shadow-none">
                    <div className="w-12 h-12 rounded-2xl bg-blue-50 dark:bg-blue-500/10 flex items-center justify-center mb-4 text-blue-600 dark:text-blue-400">
                        <ImageIcon className="w-6 h-6" />
                    </div>
                    <h3 className="font-bold text-lg mb-2 dark:text-white">Visuals Preserved</h3>
                    <p className="text-sm text-modern-neutral-500 dark:text-modern-neutral-400 leading-relaxed">Matplotlib and Seaborn plots are automatically embedded into the final PDF.</p>
                </div>
                <div className="p-6 bg-white dark:bg-modern-neutral-900 rounded-3xl border border-modern-neutral-100 dark:border-modern-neutral-800 shadow-xl shadow-modern-neutral-100/50 dark:shadow-none">
                    <div className="w-12 h-12 rounded-2xl bg-green-50 dark:bg-green-500/10 flex items-center justify-center mb-4 text-green-600 dark:text-green-400">
                        <ShieldCheck className="w-6 h-6" />
                    </div>
                    <h3 className="font-bold text-lg mb-2 dark:text-white">Enterprise Privacy</h3>
                    <p className="text-sm text-modern-neutral-500 dark:text-modern-neutral-400 leading-relaxed">No data ever leaves your computer. Period.</p>
                </div>
            </div>

            <div className="space-y-12 mb-20">
                {sections.map((section, i) => (
                    <div key={i} className="relative pl-8 md:pl-12">
                        <div className="absolute left-0 top-0 w-1.5 h-full bg-gradient-to-b from-orange-500/10 via-orange-500 to-orange-500/10 rounded-full" />
                        <div className="flex items-center gap-4 mb-4">
                            {section.icon}
                            <h2 className="text-2xl font-bold dark:text-white">{section.title}</h2>
                        </div>
                        <p className="text-modern-neutral-600 dark:text-modern-neutral-300 mb-6 leading-relaxed max-w-3xl">
                            {section.content}
                        </p>
                        {section.steps && (
                            <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
                                {section.steps.map((step, si) => (
                                    <div key={si} className="flex gap-4 p-4 bg-modern-neutral-50 dark:bg-modern-neutral-800/50 rounded-2xl border border-modern-neutral-100 dark:border-modern-neutral-800">
                                        <span className="flex-shrink-0 w-8 h-8 rounded-full bg-orange-600 text-white flex items-center justify-center font-bold text-sm">{si + 1}</span>
                                        <p className="text-sm font-medium dark:text-modern-neutral-200">{step}</p>
                                    </div>
                                ))}
                            </div>
                        )}
                        {section.list && (
                            <ul className="grid grid-cols-1 md:grid-cols-2 gap-x-12 gap-y-3">
                                {section.list.map((item, li) => (
                                    <li key={li} className="flex items-start gap-2 text-modern-neutral-600 dark:text-modern-neutral-400">
                                        <div className="w-1.5 h-1.5 rounded-full bg-orange-500 mt-2 shrink-0" />
                                        <span className="text-sm font-medium">{item}</span>
                                    </li>
                                ))}
                            </ul>
                        )}
                    </div>
                ))}
            </div>

            <section className="mb-20 bg-modern-neutral-900 dark:bg-white rounded-3xl p-8 md:p-12 text-center overflow-hidden relative group">
                <div className="absolute top-0 right-0 w-64 h-64 bg-orange-500/10 blur-3xl rounded-full -mr-32 -mt-32 group-hover:bg-orange-500/20 transition-colors" />
                <h2 className="text-3xl font-bold text-white dark:text-modern-neutral-900 mb-4 relative z-10">
                    {lang === 'fr' ? 'Prêt à convertir ?' : 'Ready to convert your Notebook?'}
                </h2>
                <p className="text-modern-neutral-400 dark:text-modern-neutral-500 mb-8 max-w-lg mx-auto relative z-10">
                    {lang === 'fr'
                        ? 'Essayez notre convertisseur IPYNB gratuit et voyez la différence par vous-même.'
                        : 'Try our free IPYNB converter and experience the speed and privacy for yourself.'}
                </p>
                <Link
                    href={`/${lang}/ipynb-to-pdf`}
                    className="inline-flex items-center gap-2 px-8 py-4 bg-orange-600 hover:bg-orange-500 text-white rounded-2xl font-bold shadow-2xl shadow-orange-900/40 transition-all hover:scale-105 active:scale-95 group relative z-10"
                >
                    <span>{lang === 'fr' ? 'Aller au convertisseur' : 'Go to Converter'}</span>
                    <ArrowRight className="w-5 h-5 group-hover:translate-x-1 transition-transform" />
                </Link>
            </section>

            <section>
                <div className="flex items-center gap-4 mb-8">
                    <HelpCircle className="w-8 h-8 text-orange-500" />
                    <h2 className="text-3xl font-bold dark:text-white">FAQ</h2>
                </div>
                <div className="grid grid-cols-1 md:grid-cols-2 gap-8">
                    {faqs.map((faq, i) => (
                        <div key={i} className="p-6 bg-white dark:bg-modern-neutral-900 rounded-3xl border border-modern-neutral-100 dark:border-modern-neutral-800 hover:border-orange-500/30 transition-colors">
                            <h4 className="font-bold text-lg mb-3 dark:text-white underline decoration-orange-500/30 underline-offset-4">{faq.q}</h4>
                            <p className="text-sm text-modern-neutral-600 dark:text-modern-neutral-400 leading-relaxed font-medium">{faq.a}</p>
                        </div>
                    ))}
                </div>
            </section>
        </div>
    );
};
