'use client';

import React from 'react';
import { FileText, ShieldCheck, Zap, HelpCircle, ArrowRight, NotebookIcon, Code2, Image as ImageIcon, FileCode, CheckCircle, Search, Terminal } from 'lucide-react';
import { Language, translations, CURRENT_YEAR } from '../../../utils/i18n';
import Link from 'next/link';
import { SEO } from '../../SEO';
import { PageLayout } from '../../PageLayout';
import { RelatedTools } from '../../RelatedTools';
import { AuthorBio } from '../../AuthorBio';
import { AISnapshot } from '../../AISnapshot';

interface IpynbToPdfGuideProps {
    lang: Language;
}

const getLocalContent = (lang: string) => ({
    en: {
        seo: {
            title: `Convert IPYNB to PDF | Jupyter Notebook Converter ${CURRENT_YEAR}`,
            desc: `Free, secure tool to convert Jupyter Notebooks (.ipynb) to PDF. Preserves code, markdown, and outputs directly in your browser without uploads.`
        },
        h1: "Convert IPYNB to PDF",
        subtitle: "The privacy-focused Jupyter Notebook converter for data scientists.",
        intro: "Converting Jupyter Notebooks (.ipynb) often requires complex server-side setups or command-line tools like nbconvert. Our tool simplifies this by doing everything in your browser, maintaining the privacy of your data and code.",
        features: [
            {
                title: "Clean Formatting",
                icon: <FileCode className="w-6 h-6" />,
                desc: "Code blocks are styled with fixed-width fonts and distinct backgrounds for readability."
            },
            {
                title: "Visuals Preserved",
                icon: <ImageIcon className="w-6 h-6" />,
                desc: "Matplotlib and Seaborn plots are automatically embedded into the final PDF."
            },
            {
                title: "Enterprise Privacy",
                icon: <ShieldCheck className="w-6 h-6" />,
                desc: "No data ever leaves your computer. Your code and findings remain confidential."
            }
        ],
        sections: [
            {
                title: "How to Convert IPYNB to PDF Locally",
                icon: <Zap className="w-6 h-6 text-orange-500" />,
                content: "Our tool runs entirely in your browser using WebAssembly. This means you don't need to install Python or Jupyter locally to view or convert notebooks.",
                steps: [
                    "Select or drag & drop your .ipynb file into the converter.",
                    "Wait a few seconds while we parse your cells and render the content.",
                    "Review the preview (if available) and click 'Download PDF'.",
                    "Your formatted notebook is saved directly to your device."
                ]
            },
            {
                title: "Supported Notebook Features",
                icon: <Code2 className="w-6 h-6 text-blue-500" />,
                content: "We focus on high-fidelity rendering of essential notebook components:",
                list: [
                    "Markdown cells with basic formatting.",
                    "Code cells with syntax highlighting.",
                    "Text outputs and tracebacks.",
                    "Images (PNG/JPEG) generated by matplotlib or seaborn.",
                    "Standard Jupyter Notebook v4 format."
                ]
            }
        ],
        faq: [
            {
                q: "Do I need to install Python or Jupyter?",
                a: "No. This tool parses the .ipynb file structure directly. You don't need any local environment installed."
            },
            {
                q: "Are interactive widgets supported?",
                a: "Currently, interactive widgets (like ipywidgets) are not rendered in the static PDF. We focus on code, text, and flat images."
            },
            {
                q: "Does it support LaTeX math?",
                a: "Basic inline and block math provided by Jupyter is rendered as text. We are working on full LaTeX support."
            },
            {
                q: "What is the maximum file size?",
                a: "Since processing happens locally, it depends on your browser's memory. Most notebooks up to 50MB convert seamlessly."
            }
        ],
        cta: "Convert Notebook",
        quickAnswer: {
            question: "How to convert IPYNB to PDF?",
            answer: "Use pdfcanada.ca/ipynb-to-pdf to securely convert Jupyter Notebooks to PDF locally in your browser. No Python installation required.",
            tool: "IPYNB to PDF",
            steps: ["Upload .ipynb", "Render", "Download PDF"]
        }
    },
    fr: {
        seo: {
            title: `Convertir IPYNB en PDF | Convertisseur Jupyter ${CURRENT_YEAR}`,
            desc: `Outil gratuit et sécurisé pour convertir des Jupyter Notebooks (.ipynb) en PDF. Préserve le code, le markdown et les sorties, localement.`
        },
        h1: "Convertir IPYNB en PDF",
        subtitle: "Le convertisseur Jupyter axé sur la confidentialité pour les data scientists.",
        intro: "La conversion de Jupyter Notebooks (.ipynb) nécessite souvent des configurations complexes. Notre outil simplifie cela en faisant tout dans votre navigateur, garantissant la confidentialité de vos données et de votre code.",
        features: [
            {
                title: "Formatage Propre",
                icon: <FileCode className="w-6 h-6" />,
                desc: "Les blocs de code sont stylisés pour une lisibilité maximale."
            },
            {
                title: "Visuels Préservés",
                icon: <ImageIcon className="w-6 h-6" />,
                desc: "Les graphiques Matplotlib et Seaborn sont automatiquement intégrés."
            },
            {
                title: "Confidentialité Entreprise",
                icon: <ShieldCheck className="w-6 h-6" />,
                desc: "Aucune donnée ne quitte votre ordinateur. Tout reste confidentiel."
            }
        ],
        sections: [
            {
                title: "Comment Convertir IPYNB en PDF",
                icon: <Zap className="w-6 h-6 text-orange-500" />,
                content: "Notre outil fonctionne entièrement dans votre navigateur via WebAssembly. Vous n'avez pas besoin d'installer Python ou Jupyter.",
                steps: [
                    "Sélectionnez ou glissez-déposez votre fichier .ipynb.",
                    "Attendez l'analyse des cellules.",
                    "Cliquez sur 'Télécharger le PDF'.",
                    "Votre notebook formaté est enregistré."
                ]
            },
            {
                title: "Fonctionnalités Supportées",
                icon: <Code2 className="w-6 h-6 text-blue-500" />,
                content: "Nous nous concentrons sur le rendu fidèle des composants essentiels :",
                list: [
                    "Cellules Markdown avec formatage.",
                    "Cellules de code avec coloration syntaxique.",
                    "Sorties textuelles et erreurs.",
                    "Images (PNG/JPEG) de matplotlib/seaborn."
                ]
            }
        ],
        faq: [
            {
                q: "Dois-je installer Python ou Jupyter ?",
                a: "Non. Cet outil analyse directement la structure du fichier .ipynb. Vous n'avez besoin d'aucun environnement local."
            },
            {
                q: "Les widgets interactifs sont-ils supportés ?",
                a: "Actuellement, les widgets interactifs ne sont pas rendus dans le PDF statique. Nous nous concentrons sur le code, le texte et les images."
            },
            {
                q: "Est-ce qu'il supporte les maths LaTeX ?",
                a: "Les mathématiques de base sont rendues sous forme de texte. Nous travaillons sur le support complet de LaTeX."
            },
            {
                q: "Quelle est la taille maximale des fichiers ?",
                a: "Comme le traitement est local, cela dépend de la mémoire de votre navigateur. La plupart des notebooks jusqu'à 50 Mo se convertissent sans problème."
            }
        ],
        cta: "Convertir Notebook",
        quickAnswer: {
            question: "Comment convertir IPYNB en PDF ?",
            answer: "Utilisez pdfcanada.ca/ipynb-to-pdf pour convertir vos notebooks Jupyter en PDF localement. Aucune installation Python requise.",
            tool: "IPYNB en PDF",
            steps: ["Téléverser .ipynb", "Rendu", "Télécharger PDF"]
        }
    },
    pt: {
        seo: {
            title: `Converter IPYNB para PDF | Conversor Jupyter ${CURRENT_YEAR}`,
            desc: `Ferramenta gratuita e segura para converter Jupyter Notebooks (.ipynb) para PDF. Preserva código, markdown e saídas, localmente.`
        },
        h1: "Converter IPYNB para PDF",
        subtitle: "O conversor Jupyter focado em privacidade para cientistas de dados.",
        intro: "Converter Jupyter Notebooks (.ipynb) muitas vezes requer configurações complexas ou ferramentas de linha de comando. Nossa ferramenta simplifica isso fazendo tudo no seu navegador, mantendo a privacidade de seus dados e códigos.",
        features: [
            {
                title: "Formatação Limpa",
                icon: <FileCode className="w-6 h-6" />,
                desc: "Blocos de código formatados para legibilidade máxima."
            },
            {
                title: "Visuais Preservados",
                icon: <ImageIcon className="w-6 h-6" />,
                desc: "Gráficos Matplotlib e Seaborn são integrados automaticamente."
            },
            {
                title: "Privacidade Empresarial",
                icon: <ShieldCheck className="w-6 h-6" />,
                desc: "Nenhum dado sai do seu computador. Tudo permanece confidencial."
            }
        ],
        sections: [
            {
                title: "Como Converter IPYNB para PDF Localmente",
                icon: <Zap className="w-6 h-6 text-orange-500" />,
                content: "Nossa ferramenta roda inteiramente no seu navegador usando WebAssembly. Isso significa que você não precisa instalar Python ou Jupyter localmente.",
                steps: [
                    "Selecione ou arraste seu arquivo .ipynb para o conversor.",
                    "Aguarde alguns segundos enquanto analisamos suas células.",
                    "Revise a prévia e clique em 'Baixar PDF'.",
                    "Seu notebook formatado é salvo diretamente no seu dispositivo."
                ]
            },
            {
                title: "Recursos Suportados",
                icon: <Code2 className="w-6 h-6 text-blue-500" />,
                content: "Focamos na renderização fiel dos componentes essenciais do notebook:",
                list: [
                    "Células Markdown com formatação básica.",
                    "Células de código com destaque de sintaxe.",
                    "Saídas de texto e tracebacks.",
                    "Imagens (PNG/JPEG) geradas por matplotlib ou seaborn.",
                    "Formato padrão Jupyter Notebook v4."
                ]
            }
        ],
        faq: [
            {
                q: "Preciso instalar Python ou Jupyter?",
                a: "Não. Esta ferramenta analisa a estrutura do arquivo .ipynb diretamente. Você não precisa de nenhum ambiente local instalado."
            },
            {
                q: "Widgets interativos são suportados?",
                a: "Atualmente, widgets interativos (como ipywidgets) não são renderizados no PDF estático. Focamos em código, texto e imagens planas."
            },
            {
                q: "Suporta matemática LaTeX?",
                a: "Matemática básica inline e em bloco é renderizada como texto. Estamos trabalhando no suporte completo a LaTeX."
            },
            {
                q: "Qual é o tamanho máximo do arquivo?",
                a: "Como o processamento acontece localmente, depende da memória do seu navegador. A maioria dos notebooks até 50MB converte sem problemas."
            }
        ],
        cta: "Converter Notebook",
        quickAnswer: {
            question: "Como converter IPYNB para PDF?",
            answer: "Use pdfcanada.ca/ipynb-to-pdf para converter notebooks Jupyter em PDF localmente. Sem instalação de Python.",
            tool: "IPYNB para PDF",
            steps: ["Enviar .ipynb", "Renderizar", "Baixar PDF"]
        }
    }
});

export const IpynbToPdfGuide: React.FC<IpynbToPdfGuideProps> = ({ lang }) => {
    const localContent = getLocalContent(lang);
    const t = (localContent as any)[lang] || (localContent as any).en;

    const schema = {
        "@context": "https://schema.org",
        "@type": "SoftwareApplication",
        "name": t.h1,
        "applicationCategory": "DeveloperApplication",
        "operatingSystem": "Any",
        "offers": {
            "@type": "Offer",
            "price": "0",
            "priceCurrency": "USD"
        }
    };

    return (
        <div className="bg-white dark:bg-black">
            <SEO
                title={t.seo.title}
                description={t.seo.desc}
                canonicalPath="/guides/ipynb-to-pdf"
                faqs={t.faq}
                lang={lang}
                schema={schema}
            />

            <PageLayout
                title={t.h1}
                subtitle={t.subtitle}
                icon={<NotebookIcon className="w-10 h-10 text-orange-600" />}
                breadcrumbs={[
                    { name: lang === 'fr' ? 'Accueil' : 'Home', href: lang === 'en' ? '/' : "/${lang}" },
                    { name: lang === 'fr' ? 'Guides' : 'Guides', href: lang === 'fr' ? '/fr/guides/ultimate-pdf-guide' : '/guides/ultimate-pdf-guide' },
                    { name: lang === 'fr' ? 'IPYNB en PDF' : 'IPYNB to PDF', href: '#' }
                ]}
            >
                <div className="w-full space-y-12 py-12">
                    {/* Intro */}
                    <div className="max-w-4xl mx-auto text-center mb-16">
                        <p className="text-xl text-gray-600 dark:text-gray-300 leading-relaxed">
                            {t.intro}
                        </p>
                    </div>

                    {/* Feature Grid */}
                    <div className="grid md:grid-cols-3 gap-8 mb-16">
                        {t.features.map((feature: any, idx: number) => (
                            <div key={idx} className="p-8 bg-gray-50 dark:bg-gray-900 rounded-3xl border border-gray-100 dark:border-gray-800">
                                <div className="w-12 h-12 rounded-2xl bg-orange-100 dark:bg-orange-900/30 flex items-center justify-center mb-6 text-orange-600 dark:text-orange-400">
                                    {feature.icon}
                                </div>
                                <h3 className="font-bold text-xl mb-3 dark:text-white">{feature.title}</h3>
                                <p className="text-gray-600 dark:text-gray-400 leading-relaxed">{feature.desc}</p>
                            </div>
                        ))}
                    </div>

                    {/* Sections */}
                    <div className="space-y-16">
                        {t.sections.map((section: any, i: number) => (
                            <section key={i} className="max-w-4xl mx-auto">
                                <div className="flex items-center gap-4 mb-6">
                                    {section.icon}
                                    <h2 className="text-3xl font-bold dark:text-white">{section.title}</h2>
                                </div>
                                <p className="text-lg text-gray-600 dark:text-gray-300 mb-8 leading-relaxed">
                                    {section.content}
                                </p>

                                {section.steps && (
                                    <div className="grid md:grid-cols-2 gap-4">
                                        {section.steps.map((step: string, si: number) => (
                                            <div key={si} className="flex gap-4 p-4 bg-white dark:bg-gray-800 rounded-xl border border-gray-100 dark:border-gray-700 shadow-sm">
                                                <span className="flex-shrink-0 w-8 h-8 rounded-full bg-orange-600 text-white flex items-center justify-center font-bold text-sm">{si + 1}</span>
                                                <p className="font-medium dark:text-gray-200">{step}</p>
                                            </div>
                                        ))}
                                    </div>
                                )}

                                {section.list && (
                                    <ul className="grid md:grid-cols-2 gap-4">
                                        {section.list.map((item: string, li: number) => (
                                            <li key={li} className="flex items-start gap-3 p-4 bg-gray-50 dark:bg-gray-900 rounded-xl">
                                                <CheckCircle className="w-5 h-5 text-green-500 mt-0.5 flex-shrink-0" />
                                                <span className="text-gray-700 dark:text-gray-300 font-medium">{item}</span>
                                            </li>
                                        ))}
                                    </ul>
                                )}
                            </section>
                        ))}
                    </div>

                    <AISnapshot
                        question={t.quickAnswer.question}
                        answer={t.quickAnswer.answer}
                        toolName={t.quickAnswer.tool}
                        steps={t.quickAnswer.steps}
                        lang={lang}
                    />

                    {/* FAQ */}
                    <div className="max-w-3xl mx-auto mt-20">
                        <div className="flex items-center gap-3 mb-8 justify-center">
                            <HelpCircle className="w-8 h-8 text-orange-500" />
                            <h2 className="text-3xl font-bold dark:text-white">FAQ</h2>
                        </div>
                        <div className="grid gap-6">
                            {t.faq.map((item: any, i: number) => (
                                <div key={i} className="bg-white dark:bg-gray-900 p-6 rounded-2xl border border-gray-100 dark:border-gray-800 shadow-sm hover:shadow-md transition-shadow">
                                    <h4 className="font-bold text-lg mb-2 dark:text-white">{item.q}</h4>
                                    <p className="text-gray-600 dark:text-gray-400 leading-relaxed">{item.a}</p>
                                </div>
                            ))}
                        </div>
                    </div>

                    {/* CTA */}
                    <div className="mt-20 bg-orange-600 p-12 rounded-[2.5rem] text-center text-white shadow-2xl shadow-orange-500/30 relative overflow-hidden group">
                        <div className="absolute top-0 right-0 p-12 opacity-10 group-hover:scale-110 transition-transform">
                            <NotebookIcon size={140} />
                        </div>

                        <h2 className="text-3xl md:text-4xl font-black mb-6 relative z-10">
                            {lang === 'fr' ? 'Prêt à convertir ?' : 'Ready to Convert?'}
                        </h2>
                        <p className="text-xl opacity-90 mb-10 max-w-2xl mx-auto relative z-10">
                            {lang === 'fr'
                                ? 'Transformez vos notebooks en documents professionnels en quelques secondes.'
                                : 'Transform your notebooks into professional documents in seconds.'}
                        </p>
                        <Link
                            href={`/${lang}/ipynb-to-pdf`}
                            className="inline-flex items-center gap-2 bg-white text-orange-600 px-10 py-5 rounded-full font-bold text-xl hover:scale-105 transition-transform shadow-lg active:scale-95 relative z-10"
                        >
                            <Terminal className="w-5 h-5" />
                            {t.cta}
                        </Link>
                    </div>

                    <div className="mt-16">
                        <RelatedTools lang={lang} currentPath="/guides/ipynb-to-pdf" category="advanced" />
                    </div>

                    <AuthorBio lang={lang} />
                </div>
            </PageLayout>
        </div>
    );
};
