
'use client';

import Link from 'next/link';
import React from 'react';
import { FileCode, Globe, CheckCircle, Info, Database, Lock, Search } from 'lucide-react';
import { Language, CURRENT_YEAR } from '../../../utils/i18n';
import { SEO } from '../../SEO';
import { PageLayout } from '../../PageLayout';
import { AuthorBio } from '../../AuthorBio';
import { RelatedTools } from '../../RelatedTools';
import { AISnapshot } from '../../AISnapshot';
import { MarkdownContent } from '../../MarkdownContent';

interface GuideProps {
    lang: Language;
}

const getGuideContent = (lang: Language) => ({
    en: {
        seo: {
            title: `Free PDF to UBL Converter | Create E-Invoices ${CURRENT_YEAR} | pdfcanada.ca`,
            desc: `Convert PDF invoices to UBL 2.1 XML format for free. Generate standard-compliant e-invoices locally in your browser. No uploads, 100% private.`
        },
        h1: `Free PDF to UBL Converter (${CURRENT_YEAR})`,
        subtitle: "The complete guide to creating compliant UBL 2.1 XML invoices from your PDF documents.",

        intro: `In the modern world of business, sending a PDF invoice isn't always enough. Many governments and enterprise systems now require **Electronic Invoicing** in structured formats like **UBL (Universal Business Language)**.

At **pdfcanada.ca**, we've built a simple, private way to convert your human-readable PDF invoices into machine-readable UBL XML files. Whether you're a freelancer dealing with a large government contract or a small business needing to modernize your billing, our **PDF to UBL** tool is here to help.

Best of all, we respect your privacy. All extraction and XML generation happens right on your device. Your sensitive financial data never touches a server.`,

        sections: [
            {
                id: "what-is-ubl",
                title: "What is UBL (Universal Business Language)?",
                content: `**UBL** is a standard XML format for business documents like invoices and purchase orders. Unlike a PDF, which is a "picture" of a document, UBL is structured data that computers can read automatically.

**Why use UBL?**
*   **Automation:** Systems can import UBL invoices directly without manual entry.
*   **Compliance:** It's the standard for Electronic Invoicing (E-Invoicing) in many regions (like PEPPOL in Europe).
*   **Accuracy:** Reduces errors caused by manual typing.`
            },
            {
                id: "how-to",
                title: "How to Convert PDF Invoice to UBL XML",
                content: `Using our **PDF to UBL** converter is fast and secure. Here is how it works:

### Step 1: Upload Your Invoice
Go to our [PDF to UBL Tool](/${lang}/pdf-to-ubl) and upload your PDF invoice. We support standard PDF invoices generated by most accounting software.

### Step 2: Automatic Data Extraction
Our local AI scans your document for key information:
*   **Vendor Name:** Who is sending the invoice.
*   **Invoice ID:** The unique reference number.
*   **Date:** When the invoice was issued.
*   **Amounts:** Subtotal, Tax, and Total, including Currency.

### Step 3: Verify and Edit
Because every PDF is different, we show you the extracted data for verification. specific UBL fields are strict, so ensuring the **Date** format (YYYY-MM-DD) and **Currency** code (e.g., USD, EUR) are correct is important. You can edit any field directly in our interface.

### Step 4: Download UBL XML
Click **Download UBL XML** to generate the final file. This file is compliant with UBL 2.1 standards and can be imported into compatible accounting systems.`
            },
            {
                id: "compliance",
                title: "E-Invoicing Compliance",
                content: `While our tool generates valid **UBL 2.1** XML, e-invoicing requirements vary by country and network (like PEPPOL).

*   **Structure:** We use the standard UBL Invoice-2 schema.
*   **Validation:** We recommend validating the generated XML against your specific partner's requirements.
*   **Privacy:** Since we process locally, you maintain full control over your compliance data.`
            }
        ],

        faq: [
            {
                q: "Is this tool free?",
                a: "Yes! The PDF to UBL converter is 100% free to use. Unlimited conversions, no sign-ups."
            },
            {
                q: "What version of UBL do you support?",
                a: "We generate UBL version 2.1 XML files, which is the widely accepted standard for electronic invoicing."
            },
            {
                q: "Is my data secure?",
                a: "Absolutely. The conversion happens entirely in your browser. We never upload your invoice to any server."
            },
            {
                q: "Can I edit the extracted data?",
                a: "Yes! You can review and modify all extracted fields (Vendor, Date, Amounts) before generating the XML to ensure accuracy."
            }
        ],

        ctaTitle: "Start Creating E-Invoices",
        ctaButton: "Convert PDF to UBL",
        ctaSubtext: "Fast, Free, and Private."
    },
    fr: {
        seo: {
            title: `Convertisseur PDF vers UBL Gratuit | Facture Électronique ${CURRENT_YEAR} | pdfcanada.ca`,
            desc: `Convertissez vos factures PDF au format UBL 2.1 XML gratuitement. Générez des factures électroniques conformes localement. 100% privé.`
        },
        h1: `Convertisseur PDF vers UBL Gratuit (${CURRENT_YEAR})`,
        subtitle: "Le guide complet pour créer des factures UBL 2.1 XML conformes à partir de vos documents PDF.",

        intro: `Dans le monde des affaires moderne, envoyer une simple facture PDF ne suffit plus toujours. De nombreux gouvernements et grandes entreprises exigent désormais la **Facturation Électronique** dans des formats structurés comme **UBL (Universal Business Language)**.

Chez **pdfcanada.ca**, nous avons créé un moyen simple et privé de convertir vos factures PDF lisibles par l'humain en fichiers XML UBL lisibles par la machine.

Le meilleur ? Nous respectons votre vie privée. Toute l'extraction et la génération XML se font directement sur votre appareil.`,

        sections: [
            {
                id: "what-is-ubl",
                title: "Qu'est-ce que l'UBL ?",
                content: `**UBL** est un format XML standard pour les documents commerciaux. Contrairement à un PDF, qui est une « image » d'un document, l'UBL est constitué de données structurées que les ordinateurs peuvent lire automatiquement.

**Pourquoi utiliser UBL ?**
*   **Automatisation :** Import direct dans les systèmes comptables.
*   **Conformité :** Standard pour la facturation électronique (PEPPOL en Europe, etc.).
*   **Précision :** Réduit les erreurs de saisie manuelle.`
            },
            {
                id: "how-to",
                title: "Comment convertir une facture PDF en UBL XML",
                content: `Utiliser notre convertisseur **PDF vers UBL** est rapide et sécurisé :

### Étape 1 : Importez votre facture
Allez sur notre [Outil PDF vers UBL](/${lang}/pdf-to-ubl) et téléversez votre facture PDF.

### Étape 2 : Extraction automatique
Notre IA locale scanne votre document pour trouver les informations clés (Vendeur, Date, Montants).

### Étape 3 : Vérifiez et modifiez
Vérifiez les données extraites. Assurez-vous que le format de la **Date** (AAAA-MM-JJ) et le code **Devise** (ex: CAD, EUR) sont corrects.

### Étape 4 : Téléchargez le XML UBL
Cliquez sur **Télécharger XML UBL** pour générer le fichier conforme aux normes UBL 2.1.`
            }
        ],

        faq: [
            {
                q: "Est-ce gratuit ?",
                a: "Oui ! Le convertisseur PDF vers UBL est 100% gratuit. Conversions illimitées."
            },
            {
                q: "Quelle version d'UBL supportez-vous ?",
                a: "Nous générons des fichiers XML UBL version 2.1, le standard largement accepté."
            },
            {
                q: "Mes données sont-elles sécurisées ?",
                a: "Absolument. La conversion se fait entièrement dans votre navigateur. Nous ne téléversons jamais votre facture."
            }
        ],

        ctaTitle: "Créez vos Factures Électroniques",
        ctaButton: "Convertir PDF en UBL",
        ctaSubtext: "Rapide, Gratuit et Privé."
    }
});

export const PdfToUblGuide: React.FC<GuideProps> = ({ lang }) => {
    const guideContent = getGuideContent(lang);
    const t = guideContent[lang as keyof typeof guideContent] || guideContent.en;

    const schema = {
        "@context": "https://schema.org",
        "@type": "SoftwareApplication",
        "name": t.h1,
        "operatingSystem": "All",
        "applicationCategory": "BusinessApplication",
        "offers": {
            "@type": "Offer",
            "price": "0",
            "priceCurrency": "USD"
        }
    };

    return (
        <div className="bg-white dark:bg-gray-950">
            <SEO
                title={t.seo.title}
                description={t.seo.desc}
                canonicalPath="/guides/pdf-to-ubl"
                faqs={t.faq}
                lang={lang}
                schema={schema}
                quickAnswer={{
                    question: lang === 'fr' ? "Comment convertir un PDF en UBL XML ?" : "How to convert PDF to UBL XML?",
                    answer: lang === 'fr'
                        ? "Utilisez l'outil PDF vers UBL de pdfcanada.ca. Importez votre facture, vérifiez les données extraites et téléchargez le fichier XML UBL 2.1."
                        : "Use pdfcanada.ca's PDF to UBL tool. Upload your invoice, verify the extracted data, and download the UBL 2.1 XML file.",
                    tool: "PDF to UBL Tool",
                    steps: lang === 'fr'
                        ? ["Importez le PDF", "Vérifiez les données", "Téléchargez UBL XML"]
                        : ["Upload PDF", "Verify Data", "Download UBL XML"],
                }}
                breadcrumbs={[
                    { name: lang === 'fr' ? 'Accueil' : 'Home', path: lang === 'fr' ? '/fr' : '/' },
                    { name: lang === 'fr' ? 'Guides' : 'Guides', path: lang === 'fr' ? '/fr/guides/ultimate-pdf-guide' : '/guides/ultimate-pdf-guide' },
                    { name: lang === 'fr' ? 'PDF vers UBL' : 'PDF to UBL', path: lang === 'fr' ? '/fr/guides/pdf-to-ubl' : '/guides/pdf-to-ubl' }
                ]}
            />
            <PageLayout
                title={t.h1}
                subtitle={t.subtitle}
                icon={<FileCode size={32} />}
                breadcrumbs={[
                    { name: lang === 'fr' ? 'Accueil' : 'Home', href: lang === 'fr' ? '/fr' : '/' },
                    { name: lang === 'fr' ? 'Guides' : 'Guides', href: lang === 'fr' ? '/fr/guides/ultimate-pdf-guide' : '/guides/ultimate-pdf-guide' },
                    { name: lang === 'fr' ? 'PDF vers UBL' : 'PDF to UBL', href: '#' }
                ]}
            >
                <div className="max-w-4xl mx-auto py-8">
                    <div className="text-xl leading-relaxed text-gray-600 dark:text-gray-400 mb-16">
                        <MarkdownContent content={t.intro} />
                    </div>

                    <div className="grid md:grid-cols-3 gap-8 mb-20">
                        <div className="p-8 bg-gray-50 dark:bg-gray-900 rounded-[2rem] border border-gray-100 dark:border-gray-800 shadow-sm">
                            <Database className="text-canada-red mb-4" size={32} />
                            <h3 className="text-xl font-bold mb-2">UBL 2.1</h3>
                            <p className="text-gray-500">{lang === 'fr' ? "Format standardisé." : "Standardized format."}</p>
                        </div>
                        <div className="p-8 bg-gray-50 dark:bg-gray-900 rounded-[2rem] border border-gray-100 dark:border-gray-800 shadow-sm">
                            <Globe className="text-canada-red mb-4" size={32} />
                            <h3 className="text-xl font-bold mb-2">{lang === 'fr' ? "E-Invoicing" : "E-Invoicing"}</h3>
                            <p className="text-gray-500">{lang === 'fr' ? "Prêt pour l'automatisation." : "Ready for automation."}</p>
                        </div>
                        <div className="p-8 bg-gray-50 dark:bg-gray-900 rounded-[2rem] border border-gray-100 dark:border-gray-800 shadow-sm">
                            <Lock className="text-canada-red mb-4" size={32} />
                            <h3 className="text-xl font-bold mb-2">{lang === 'fr' ? "100% Privé" : "100% Private"}</h3>
                            <p className="text-gray-500">{lang === 'fr' ? "Traitement local." : "Local processing."}</p>
                        </div>
                    </div>

                    <div className="space-y-16">
                        {t.sections.map((section: any) => (
                            <section key={section.id} id={section.id} className="scroll-mt-24">
                                <h2 className="text-3xl font-black mb-6 flex items-center gap-3">
                                    <div className="w-2 h-8 bg-canada-red rounded-full" />
                                    {section.title}
                                </h2>
                                <div className="prose prose-xl dark:prose-invert max-w-none text-gray-600 dark:text-gray-400">
                                    <MarkdownContent content={section.content} />
                                </div>
                            </section>
                        ))}
                    </div>

                    <div className="my-20">
                        <div className="flex items-center gap-3 mb-10">
                            <Info className="text-canada-red" size={32} />
                            <h2 className="text-3xl font-black text-gray-900 dark:text-white">FAQ</h2>
                        </div>
                        <div className="grid gap-6">
                            {t.faq.map((item: any, i: number) => (
                                <div key={i} className="p-8 bg-white dark:bg-gray-900 rounded-3xl border border-gray-100 dark:border-gray-800 shadow-sm group hover:border-canada-red/30 transition-colors">
                                    <h4 className="text-xl font-bold mb-4 text-gray-900 dark:text-white group-hover:text-canada-red transition-colors">
                                        {item.q}
                                    </h4>
                                    <div className="text-lg text-gray-600 dark:text-gray-400 leading-relaxed">
                                        {item.a}
                                    </div>
                                </div>
                            ))}
                        </div>
                    </div>

                    <div className="mt-20 bg-canada-red p-8 md:p-12 rounded-[2.5rem] md:rounded-[3rem] text-center text-white shadow-2xl shadow-red-500/20">
                        <h2 className="text-3xl md:text-4xl font-black mb-6 leading-tight">{t.ctaTitle}</h2>
                        <p className="text-lg md:text-xl mb-10 opacity-90">{t.ctaSubtext}</p>
                        <Link href={`/${lang}/pdf-to-ubl`}
                            className="inline-block bg-white text-canada-red px-10 md:px-12 py-4 md:py-5 rounded-full font-black text-lg md:text-xl hover:scale-105 transition-all shadow-lg active:scale-95"
                        >
                            {t.ctaButton}
                        </Link>
                    </div>

                    <AISnapshot
                        question={lang === 'fr' ? "Comment convertir un PDF facture en UBL ?" : "How to convert PDF invoice to UBL?"}
                        answer={lang === 'fr'
                            ? "Utilisez l'outil PDF vers UBL de pdfcanada.ca pour générer des fichiers XML UBL directement depuis votre navigateur."
                            : "Use pdfcanada.ca's PDF to UBL tool to generate UBL XML files directly from your browser."}
                        toolName="PDF to UBL Tool"
                        steps={lang === 'fr'
                            ? ["Sélectionnez le PDF", "Vérifiez les données", "Téléchargez XML"]
                            : ["Select PDF", "Verify Data", "Download XML"]}
                        lang={lang}
                    />

                    <RelatedTools lang={lang} currentPath="/guides/pdf-to-ubl" />

                    <AuthorBio lang={lang} />
                </div>
            </PageLayout>
        </div>
    );
};
