'use client';

import Link from 'next/link';
import React from 'react';
import { FileCode, Globe, CheckCircle, Info, Database, Lock, Search, FileText } from 'lucide-react';
import { Language, CURRENT_YEAR } from '../../../utils/i18n';
import { SEO } from '../../SEO';
import { PageLayout } from '../../PageLayout';
import { AuthorBio } from '../../AuthorBio';
import { RelatedTools } from '../../RelatedTools';
import { AISnapshot } from '../../AISnapshot';
import { MarkdownContent } from '../../MarkdownContent';

interface GuideProps {
    lang: Language;
}

const getLocalContent = (lang: string) => ({
    en: {
        seo: {
            title: `Free PDF to UBL Converter | Create E-Invoices ${CURRENT_YEAR}`,
            desc: `Convert PDF invoices to UBL 2.1 XML format for free. Generate standard-compliant e-invoices locally in your browser. No uploads, 100% private.`
        },
        h1: `Free PDF to UBL Converter`,
        subtitle: "The complete guide to creating compliant UBL 2.1 XML invoices from your PDF documents.",

        intro: `In the modern world of business, sending a PDF invoice isn't always enough. Many governments and enterprise systems now require **Electronic Invoicing** in structured formats like **UBL (Universal Business Language)**.

At **pdfcanada.ca**, we've built a simple, private way to convert your human-readable PDF invoices into machine-readable UBL XML files. Whether you're a freelancer dealing with a large government contract or a small business needing to modernize your billing, our **PDF to UBL** tool is here to help.`,

        sections: [
            {
                id: "what-is-ubl",
                title: "What is UBL (Universal Business Language)?",
                content: `**UBL** is a standard XML format for business documents like invoices and purchase orders. Unlike a PDF, which is a "picture" of a document, UBL is structured data that computers can read automatically.

**Why use UBL?**
*   **Automation:** Systems can import UBL invoices directly without manual entry.
*   **Compliance:** It's the standard for Electronic Invoicing (E-Invoicing) in many regions (like Peppol in Europe).
*   **Accuracy:** Reduces errors caused by manual typing.`
            },
            {
                id: "how-to",
                title: "How to Convert PDF Invoice to UBL XML",
                content: `Using our **PDF to UBL** converter is fast and secure. Here is how it works:

### Step 1: Upload Your Invoice
Go to our **PDF to UBL Tool** and upload your PDF invoice. We support standard PDF invoices generated by most accounting software.

### Step 2: Automatic Data Extraction
Our local AI scans your document for key information: Vendor Name, Invoice ID, Date, and Amounts.

### Step 3: Verify and Edit
Because every PDF is different, we show you the extracted data for verification. Ensuring the date format (YYYY-MM-DD) and currency code are correct is important.

### Step 4: Download UBL XML
Click **Download UBL XML** to generate the final file. This file is compliant with UBL 2.1 standards.`
            },
            {
                id: "compliance",
                title: "E-Invoicing Compliance",
                content: `While our tool generates valid **UBL 2.1** XML, e-invoicing requirements vary by country and network (like Peppol).

*   **Structure:** We use the standard UBL Invoice-2 schema.
*   **Privacy:** Since we process locally, you maintain full control over your compliance data.`
            }
        ],

        faq: [
            {
                q: "Is this tool free?",
                a: "Yes! The PDF to UBL converter is 100% free to use. Unlimited conversions, no sign-ups."
            },
            {
                q: "What version of UBL do you support?",
                a: "We generate UBL version 2.1 XML files, which is the widely accepted standard for electronic invoicing."
            },
            {
                q: "Is my data secure?",
                a: "Absolutely. The conversion happens entirely in your browser. We never upload your invoice to any server."
            }
        ],

        quickAnswer: {
            question: "How to convert PDF invoice to UBL?",
            answer: "Use pdfcanada.ca's PDF to UBL tool. Upload your invoice, verify the extracted data, and download the UBL 2.1 XML file.",
            tool: "PDF to UBL Tool",
            steps: ["Upload PDF", "Verify Data", "Download UBL XML"]
        },
        ctaTitle: "Start Creating E-Invoices",
        ctaButton: "Convert PDF to UBL"
    },
    fr: {
        seo: {
            title: `Convertisseur PDF vers UBL Gratuit | Facture Électronique ${CURRENT_YEAR}`,
            desc: `Convertissez vos factures PDF au format UBL 2.1 XML gratuitement. Générez des factures électroniques conformes localement. 100% privé.`
        },
        h1: `Convertisseur PDF vers UBL Gratuit`,
        subtitle: "Le guide pour créer des factures UBL 2.1 XML conformes à partir de vos documents PDF.",

        intro: `Dans le monde des affaires moderne, envoyer une simple facture PDF ne suffit plus toujours. De nombreux gouvernements exigent désormais la **Facturation Électronique** dans des formats structurés comme **UBL**.

Chez **pdfcanada.ca**, nous avons créé un moyen simple et privé de convertir vos factures PDF lisibles par l'humain en fichiers XML UBL.`,

        sections: [
            {
                id: "what-is-ubl",
                title: "Qu'est-ce que l'UBL ?",
                content: `**UBL** est un format XML standard pour les documents commerciaux. Contrairement à un PDF, l'UBL est constitué de données structurées.

**Pourquoi utiliser UBL ?**
*   **Automatisation :** Import direct dans les systèmes comptables.
*   **Conformité :** Standard pour la facturation électronique.
*   **Précision :** Réduit les erreurs de saisie manuelle.`
            },
            {
                id: "how-to",
                title: "Comment convertir une facture en UBL",
                content: `Utiliser notre convertisseur **PDF vers UBL** est rapide et sécurisé :

### Étape 1 : Importez votre facture
Allez sur notre outil et téléversez votre facture PDF.

### Étape 2 : Extraction automatique
Notre IA locale scanne votre document pour trouver les informations clés.

### Étape 3 : Vérifiez et modifiez
Vérifiez les données extraites comme la date et les montants.

### Étape 4 : Téléchargez le XML UBL
Cliquez pour générer le fichier conforme aux normes UBL 2.1.`
            },
            {
                id: "compliance",
                title: "Conformité Facturation Électronique",
                content: `Notre outil génère du XML **UBL 2.1** valide.
*   **Structure :** Schéma standard UBL Invoice-2.
*   **Privé :** Traitement 100% local pour votre sécurité.`
            }
        ],

        faq: [
            {
                q: "Est-ce gratuit ?",
                a: "Oui ! Le convertisseur PDF vers UBL est 100% gratuit."
            },
            {
                q: "Quelle version d'UBL ?",
                a: "Nous générons des fichiers XML UBL version 2.1."
            },
            {
                q: "Mes données sont-elles sécurisées ?",
                a: "Absolument. La conversion se fait entièrement dans votre navigateur."
            }
        ],

        quickAnswer: {
            question: "Comment convertir un PDF en UBL XML ?",
            answer: "Utilisez l'outil PDF vers UBL de pdfcanada.ca. Importez votre facture, vérifiez les données et téléchargez le fichier XML UBL 2.1.",
            tool: "Outil PDF vers UBL",
            steps: ["Importez PDF", "Vérifiez Données", "Téléchargez XML"]
        },
        ctaTitle: "Créez vos Factures Électroniques",
        ctaButton: "Convertir PDF en UBL"
    },
    pt: {
        seo: {
            title: `Conversor PDF para UBL Gratuito | Fatura Eletrônica ${CURRENT_YEAR}`,
            desc: `Converta faturas PDF para o formato UBL 2.1 XML gratuitamente. Gere faturas eletrônicas compatíveis localmente no seu navegador. 100% privado.`
        },
        h1: `Conversor PDF para UBL Gratuito`,
        subtitle: "O guia completo para criar faturas UBL 2.1 XML compatíveis a partir de seus PDFs.",

        intro: `No mundo moderno dos negócios, enviar uma fatura em PDF nem sempre é suficiente. Muitos governos e empresas agora exigem **Faturamento Eletrônico** em formatos estruturados como **UBL (Universal Business Language)**.

No **pdfcanada.ca**, criamos uma maneira simples e privada de converter suas faturas PDF legíveis por humanos em arquivos XML UBL legíveis por máquina.`,

        sections: [
            {
                id: "what-is-ubl",
                title: "O que é UBL?",
                content: `**UBL** é um formato XML padrão para documentos comerciais. Diferente de um PDF, o UBL é composto por dados estruturados.

**Por que usar UBL?**
*   **Automação:** Importação direta em sistemas contábeis.
*   **Conformidade:** Padrão para faturamento eletrônico.
*   **Precisão:** Reduz erros de digitação manual.`
            },
            {
                id: "how-to",
                title: "Como converter fatura PDF para UBL XML",
                content: `Usar nosso conversor **PDF para UBL** é rápido e seguro:

### Passo 1: Envie sua Fatura
Vá para nossa ferramenta e envie sua fatura PDF.

### Passo 2: Extração Automática
Nossa IA local verifica seu documento em busca de informações importantes como Vendedor, Data e Valores.

### Passo 3: Verifique e Edite
Como cada PDF é diferente, verifique os dados extraídos para garantir precisão.

### Passo 4: Baixe o XML UBL
Clique para gerar o arquivo compatível com os padrões UBL 2.1.`
            },
            {
                id: "compliance",
                title: "Conformidade de Faturamento Eletrônico",
                content: `Nossa ferramenta gera XML **UBL 2.1** válido.
*   **Estrutura:** Esquema padrão UBL Invoice-2.
*   **Privacidade:** Processamento 100% local para sua segurança.`
            }
        ],

        faq: [
            {
                q: "É gratuito?",
                a: "Sim! O conversor PDF para UBL é 100% gratuito e ilimitado."
            },
            {
                q: "Qual versão do UBL vocês suportam?",
                a: "Geramos arquivos XML UBL versão 2.1, o padrão amplamente aceito."
            },
            {
                q: "Meus dados estão seguros?",
                a: "Absolutamente. A conversão acontece inteiramente no seu navegador. Nunca enviamos sua fatura para nenhum servidor."
            }
        ],

        quickAnswer: {
            question: "Como converter fatura PDF para UBL?",
            answer: "Use a ferramenta PDF para UBL do pdfcanada.ca. Envie sua fatura, verifique os dados e baixe o arquivo XML UBL 2.1.",
            tool: "Ferramenta PDF para UBL",
            steps: ["Enviar PDF", "Verificar Dados", "Baixar XML"]
        },
        ctaTitle: "Comece a Criar Faturas Eletrônicas",
        ctaButton: "Converter PDF para UBL"
    }
});

export const PdfToUblGuide: React.FC<GuideProps> = ({ lang }) => {
    const localContent = getLocalContent(lang);
    const t = (localContent as any)[lang] || (localContent as any).en;

    const schema = {
        "@context": "https://schema.org",
        "@type": "SoftwareApplication",
        "name": t.h1,
        "operatingSystem": "Any",
        "applicationCategory": "BusinessApplication",
        "offers": {
            "@type": "Offer",
            "price": "0",
            "priceCurrency": "USD"
        }
    };

    return (
        <PageLayout
            title={t.h1}
            subtitle={t.subtitle}
            icon={<FileCode size={32} />}
            breadcrumbs={[
                { name: lang === 'fr' ? 'Accueil' : 'Home', href: lang === 'fr' ? '/fr' : '/' },
                { name: lang === 'fr' ? 'Guides' : 'Guides', href: lang === 'fr' ? '/fr/guides/ultimate-pdf-guide' : '/guides/ultimate-pdf-guide' },
                { name: lang === 'fr' ? 'PDF ver UBL' : 'PDF to UBL', href: '#' }
            ]}
        >
            <SEO
                title={t.seo.title}
                description={t.seo.desc}
                canonicalPath="/guides/pdf-to-ubl"
                lang={lang}
                schema={schema}
                faqs={t.faq}
                quickAnswer={{
                    question: t.quickAnswer.question,
                    answer: t.quickAnswer.answer,
                    tool: t.quickAnswer.tool,
                    steps: t.quickAnswer.steps
                }}
            />

            <div className="w-full py-12">
                <div className="prose prose-xl dark:prose-invert max-w-none mb-16 text-gray-600 dark:text-gray-300">
                    <MarkdownContent content={t.intro} />
                </div>

                <div className="grid md:grid-cols-3 gap-8 mb-20">
                    <div className="p-8 bg-gray-50 dark:bg-gray-900 rounded-[2rem] border border-gray-100 dark:border-gray-800 shadow-sm">
                        <Database className="text-canada-red mb-4" size={32} />
                        <h3 className="text-xl font-bold mb-2">UBL 2.1</h3>
                        <p className="text-gray-500">{lang === 'fr' ? "Format standardisé." : lang === 'pt' ? "Formato padronizado." : "Standardized format."}</p>
                    </div>
                    <div className="p-8 bg-gray-50 dark:bg-gray-900 rounded-[2rem] border border-gray-100 dark:border-gray-800 shadow-sm">
                        <Globe className="text-canada-red mb-4" size={32} />
                        <h3 className="text-xl font-bold mb-2">{lang === 'fr' ? "E-Invoicing" : lang === 'pt' ? "Faturamento" : "E-Invoicing"}</h3>
                        <p className="text-gray-500">{lang === 'fr' ? "Prêt pour l'automatisation." : lang === 'pt' ? "Pronto para automação." : "Ready for automation."}</p>
                    </div>
                    <div className="p-8 bg-gray-50 dark:bg-gray-900 rounded-[2rem] border border-gray-100 dark:border-gray-800 shadow-sm">
                        <Lock className="text-canada-red mb-4" size={32} />
                        <h3 className="text-xl font-bold mb-2">{lang === 'fr' ? "100% Privé" : lang === 'pt' ? "100% Privado" : "100% Private"}</h3>
                        <p className="text-gray-500">{lang === 'fr' ? "Traitement local." : lang === 'pt' ? "Processamento local." : "Local processing."}</p>
                    </div>
                </div>

                <div className="space-y-16">
                    {t.sections.map((section: any) => (
                        <section key={section.id} id={section.id} className="scroll-mt-24">
                            <h2 className="text-3xl font-black mb-6 flex items-center gap-3">
                                <div className="w-2 h-8 bg-canada-red rounded-full" />
                                {section.title}
                            </h2>
                            <div className="prose prose-xl dark:prose-invert max-w-none text-gray-600 dark:text-gray-400">
                                <MarkdownContent content={section.content} />
                            </div>
                        </section>
                    ))}
                </div>

                <div className="my-20">
                    <div className="flex items-center gap-3 mb-10">
                        <Info className="text-canada-red" size={32} />
                        <h2 className="text-3xl font-black text-gray-900 dark:text-white">FAQ</h2>
                    </div>
                    <div className="grid gap-6">
                        {t.faq.map((item: any, i: number) => (
                            <div key={i} className="p-8 bg-white dark:bg-gray-900 rounded-3xl border border-gray-100 dark:border-gray-800 shadow-sm group hover:border-canada-red/30 transition-colors">
                                <h4 className="text-xl font-bold mb-4 text-gray-900 dark:text-white group-hover:text-canada-red transition-colors">
                                    {item.q}
                                </h4>
                                <div className="text-lg text-gray-600 dark:text-gray-400 leading-relaxed">
                                    {item.a}
                                </div>
                            </div>
                        ))}
                    </div>

                    <AISnapshot
                        question={t.quickAnswer.question}
                        answer={t.quickAnswer.answer}
                        toolName={t.quickAnswer.tool}
                        steps={t.quickAnswer.steps}
                        lang={lang}
                    />
                </div>

                <div className="mt-20 bg-canada-red p-8 md:p-12 rounded-[2.5rem] md:rounded-[3rem] text-center text-white shadow-2xl shadow-red-500/20">
                    <h2 className="text-3xl md:text-4xl font-black mb-6 leading-tight">{t.ctaTitle}</h2>
                    <p className="text-lg md:text-xl mb-10 opacity-90">{t.subtitle}</p>
                    <Link href={`/${lang}/pdf-to-ubl`}
                        className="inline-block bg-white text-canada-red px-10 md:px-12 py-4 md:py-5 rounded-full font-black text-lg md:text-xl hover:scale-105 transition-all shadow-lg active:scale-95"
                    >
                        {t.ctaButton}
                    </Link>
                </div>

                <div className="mt-20">
                    <RelatedTools lang={lang} currentPath="/guides/pdf-to-ubl" category="business" />
                </div>

                <div className="mt-20 border-t border-gray-200 dark:border-gray-800 pt-12">
                    <AuthorBio lang={lang} />
                </div>
            </div>
        </PageLayout>
    );
};
